CREATE VIEW MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_STATS
AS
SELECT DISTINCT
IMPLEMENTATIONCONVENTIONREF,
TRANSSETCONTROLNUM,
FILENAME,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
SUM_CLAIMFREQUENCYCODE1/SUM_TOT_REX PCT_CLAIMFREQUENCYCODE1,
SUM_STATEMENTDTP1/SUM_TOT_REX PCT_STATEMENTDTP1,
SUM_ADMISSIONDTP1/SUM_TOT_REX PCT_ADMISSIONDTP1,
SUM_BILLINGPROVNPI1/SUM_TOT_REX PCT_BILLINGPROVNPI1,
SUM_ADMITTINGDIAGNOSISCODE1/SUM_TOT_REX PCT_ADMITTINGDIAGNOSISCODE1,
SUM_FACILITYTYPECODE1/SUM_TOT_REX PCT_FACILITYTYPECODE1,
SUM_ADMISSIONTYPECODE1/SUM_TOT_REX PCT_ADMISSIONTYPECODE1,
SUM_ADMISSIONSOURCECODE1/SUM_TOT_REX PCT_ADMISSIONSOURCECODE1,
SUM_SVCLINECHARGEAMT1/SUM_TOT_REX PCT_SVCLINECHARGEAMT1,
SUM_SVCLINEREVENUECODE1/SUM_TOT_REX PCT_SVCLINEREVENUECODE1,
SUM_PATIENTSTATUSCODE1/SUM_TOT_REX PCT_PATIENTSTATUSCODE1,
SUM_CLAIMFREQUENCYCODE1,
SUM_STATEMENTDTP1,
SUM_ADMISSIONDTP1,
SUM_BILLINGPROVNPI1,
SUM_ADMITTINGDIAGNOSISCODE1,
SUM_FACILITYTYPECODE1,
SUM_ADMISSIONTYPECODE1,
SUM_ADMISSIONSOURCECODE1,
SUM_SVCLINECHARGEAMT1,
SUM_SVCLINEREVENUECODE1,
SUM_PATIENTSTATUSCODE1,
SUM_TOT_REX
FROM (
SELECT
IMPLEMENTATIONCONVENTIONREF,
TRANSSETCONTROLNUM,
FILENAME,
SUBMITTERID,
S."SubmitterLastOrgName" SUBMITTERNAME,
CLAIM_TYPE,
SUM(CLAIMFREQUENCYCODE1) SUM_CLAIMFREQUENCYCODE1,
SUM(STATEMENTDTP1) SUM_STATEMENTDTP1,
SUM(ADMISSIONDTP1) SUM_ADMISSIONDTP1,
SUM(BILLINGPROVNPI1) SUM_BILLINGPROVNPI1,
SUM(ADMITTINGDIAGNOSISCODE1) SUM_ADMITTINGDIAGNOSISCODE1,
SUM(FACILITYTYPECODE1) SUM_FACILITYTYPECODE1,
SUM(ADMISSIONTYPECODE1) SUM_ADMISSIONTYPECODE1,
SUM(ADMISSIONSOURCECODE1) SUM_ADMISSIONSOURCECODE1,
SUM(SVCLINECHARGEAMT1) SUM_SVCLINECHARGEAMT1,
SUM(SVCLINEREVENUECODE1) SUM_SVCLINEREVENUECODE1,
SUM(PATIENTSTATUSCODE1) SUM_PATIENTSTATUSCODE1,
SUM(TOT_REX) SUM_TOT_REX
FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI A
LEFT JOIN MHDWDEV.SENDPRO.RAW_SPRO_837I_FILE_STATISTICS S
    ON A.IMPLEMENTATIONCONVENTIONREF = S."ImplementationConventionRef" AND A.SUBMITTERID = S."SubmitterID"
GROUP BY
IMPLEMENTATIONCONVENTIONREF,
TRANSSETCONTROLNUM,
FILENAME,
SUBMITTERID,
S."SubmitterLastOrgName",
CLAIM_TYPE
)
ORDER BY
IMPLEMENTATIONCONVENTIONREF,
TRANSSETCONTROLNUM,
FILENAME,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE
;


--DROP VIEW MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI;

CREATE VIEW MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI
AS
SELECT
TRANSSETCONTROLNUM,
IMPLEMENTATIONCONVENTIONREF,
SUBMITTERID,
FILENAME,
PATIENTCONTROLNUM,
NUMDTL,
CLAIM_TYPE,
CLAIMFREQUENCYCODE1,
STATEMENTDTP1,
ADMISSIONDTP1,
BILLINGPROVNPI1,
ADMITTINGDIAGNOSISCODE1,
FACILITYTYPECODE1,
ADMISSIONTYPECODE1,
ADMISSIONSOURCECODE1,
SVCLINECHARGEAMT1,
SVCLINEREVENUECODE1,
PATIENTSTATUSCODE1,
TOT_REX
FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ;

--DROP VIEW MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA;

CREATE VIEW MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA
AS
SELECT
TRANSSETCONTROLNUM,
IMPLEMENTATIONCONVENTIONREF,
SUBMITTERID,
FILENAME,
PATIENTCONTROLNUM,
NUMDTL,
CLAIM_TYPE,
CLAIMFREQUENCYCODE1X,
STATEMENTDTP1X,
ADMISSIONDTP1X,
BILLINGPROVNPI1X,
ADMITTINGDIAGNOSISCODE1X,
FACILITYTYPECODE1X,
ADMISSIONTYPECODE1X,
ADMISSIONSOURCECODE1X,
SVCLINECHARGEAMT1X,
SVCLINEREVENUECODE1X,
PATIENTSTATUSCODE1X
FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ;


select * from MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ;
--drop table MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ;

CREATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ
AS
SELECT
TransSetControlNum,
ImplementationConventionRef,
SubmitterID,
PatientControlNum,
NumDtl,
claim_type,
FileName,

--PatientStatusCode,
--FacilityTypeCode,
--AdmissionDTP,

--  CLAIM_FREQ_TYPE_CD
--  DI
    CASE WHEN ClaimFrequencyCode IS NOT NULL AND ClaimFrequencyCode IN ('1','2','3','4','5','7','8') THEN 1 ELSE 0 END ClaimFrequencyCode1,
--  Ex
    CASE WHEN ClaimFrequencyCode IS NULL THEN 'NULL'
    WHEN ClaimFrequencyCode NOT IN ('1','2','3','4','5','7','8') THEN 'INVALID' 
    ELSE 'VALID' END ClaimFrequencyCode1X,
	   
--  CLAIM_STATEMENT_DTM_PERIOD
--  DI
    CASE WHEN Claim_Type in ('I','L') 
	AND StatementDTP IS NOT NULL 
	AND ( SUBSTR(StatementDTP, 9, 1) = '-' 
	AND TRY_TO_DATE(SUBSTR(StatementDTP, 1, 8),'YYYYMMDD') IS NOT NULL 
	AND TRY_TO_DATE(SUBSTR(StatementDTP, 10, 8),'YYYYMMDD') IS NOT NULL )  
        THEN 1 ELSE 0 END StatementDTP1,
--  Ex
    CASE WHEN StatementDTP IS NULL THEN 'NULL'
         WHEN ( SUBSTR(StatementDTP, 9, 1) != '-' OR TRY_TO_DATE(SUBSTR(StatementDTP, 1, 8),'YYYYMMDD') IS NULL OR TRY_TO_DATE(SUBSTR(StatementDTP, 10, 8),'YYYYMMDD') IS NULL ) THEN 'INVALID' 
		 ELSE 'VALID' END StatementDTP1X,

--  CLAIM_ADMISSION_DTM_PERIOD
--  DI		 
    CASE WHEN Claim_Type IN ('I','L') 
	AND SUBSTR(FacilityTypeCode,1,2) = '11' 
	AND AdmissionDTP IS NOT NULL 
	AND ( SUBSTR(AdmissionDTP, 9, 1) = '-' 
	AND TRY_TO_DATE(SUBSTR(AdmissionDTP, 1, 8),'YYYYMMDD') IS NOT NULL 
	AND TRY_TO_DATE(SUBSTR(AdmissionDTP, 10, 8),'YYYYMMDD') IS NOT NULL )  
        THEN 1 ELSE 0 END AdmissionDTP1,
--  Ex
--  This field should have a value if the Parameter MPT_SENDPRO_Facility_Type_Code_837I = 11

    CASE WHEN SUBSTR(FacilityTypeCode,1,2) != '11' THEN 'NOT HOSPITAL OR LTC'
	     WHEN AdmissionDTP IS NULL THEN 'NULL'
         WHEN ( SUBSTR(AdmissionDTP, 9, 1) != '-' OR TRY_TO_DATE(SUBSTR(AdmissionDTP, 1, 8),'YYYYMMDD') IS NULL OR TRY_TO_DATE(SUBSTR(AdmissionDTP, 10, 8),'YYYYMMDD') IS NULL ) THEN 'INVALID' 
		 ELSE 'VALID' END AdmissionDTP1X,
		
--  BILLING PROVIDER CODE
--  DI
    CASE WHEN BillingProvNPI IS NOT NULL
        THEN 1 ELSE 0 END BillingProvNPI1,

--  Ex
    CASE WHEN BillingProvNPI IS NULL THEN 'NULL'
		 ELSE 'VALID' END BillingProvNPI1X,
		 
--  ADMITTING DIAGNOSIS
--  DI
    CASE WHEN Claim_Type IN ('I') AND AdmittingDiagnosisCode IS NOT NULL 
	AND AdmittingDiagnosisCode IN (SELECT CDE_DIAG from MHDWDEV.NW.NW_B_DIAGNOSIS where CDE_ICD_VERSION=10 and CDE_DIAG NOT IN ('#','**','+','-')) 
	AND DiagnosisCodeQual='ABJ'
        THEN 1 ELSE 0 END AdmittingDiagnosisCode1,
--  Ex
    CASE WHEN Claim_Type NOT IN ('I') THEN 'NOT INPATIENT'
	     WHEN DiagnosisCodeQual != 'ABJ' THEN 'DiagnosisCodeQual NOT ABJ'
         WHEN AdmittingDiagnosisCode IS NULL THEN 'NULL'
		 WHEN AdmittingDiagnosisCode NOT IN (SELECT CDE_DIAG from MHDWDEV.NW.NW_B_DIAGNOSIS where CDE_ICD_VERSION=10 and CDE_DIAG NOT IN ('#','**','+','-','$','  ')) THEN 'INVALID'
         ELSE 'VALID' END AdmittingDiagnosisCode1X,
		
--  FACILITY TYPE CODE
--  DI
    CASE WHEN Claim_Type IN ('M','L','I','O') 
	AND FacilityTypeCode IS NOT NULL
    AND FacilityTypeCode IN (SELECT LEFT(CDE_CHAR,2) FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_TYPE_OF_BILL' AND CDE_CHAR NOT IN ('#','**','+','-'))
        THEN 1 ELSE 0 END FacilityTypeCode1,

--  Ex
    CASE WHEN Claim_Type NOT IN ('M','L','I','O') THEN 'NOT IN M,L,I,O'
	     WHEN FacilityTypeCode IS NULL THEN 'NULL'
         WHEN FacilityTypeCode NOT IN (SELECT LEFT(CDE_CHAR,2) FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_TYPE_OF_BILL' AND CDE_CHAR NOT IN ('#','**','+','-')) THEN 'INVALID'
         ELSE 'VALID' END FacilityTypeCode1X,
		 
--  TYPE OF ADMISSION		 
--  DI
    CASE WHEN Claim_Type IN ('L','I') 
	AND AdmissionTypeCode IS NOT NULL
    AND AdmissionTypeCode IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_ADMIT_TYPE' AND CDE_CHAR NOT IN ('#','**','+','-'))
        THEN 1 ELSE 0 END AdmissionTypeCode1,

--  Ex
    CASE WHEN Claim_Type NOT IN ('L','I') THEN 'NOT INPATIENT OR LTC'
	     WHEN AdmissionTypeCode IS NULL THEN 'NULL'
         WHEN AdmissionTypeCode NOT IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_ADMIT_TYPE' AND CDE_CHAR NOT IN ('#','**','+','-')) THEN 'INVALID'
         ELSE 'VALID' END AdmissionTypeCode1X,
		 
--  SOURCE OF ADMISSION
--  DI
    CASE WHEN Claim_Type IN ('L','I') 
	AND AdmissionSourceCode IS NOT NULL
    AND AdmissionSourceCode IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_ADMIT_SOURCE' AND CDE_CHAR NOT IN ('#','**','+','-'))
        THEN 1 ELSE 0 END AdmissionSourceCode1,

--  Ex
    CASE WHEN Claim_Type NOT IN ('L','I') THEN 'NOT INPATIENT OR LTC'
	     WHEN AdmissionSourceCode IS NULL THEN 'NULL'
         WHEN AdmissionSourceCode NOT IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_ADMIT_SOURCE' AND CDE_CHAR NOT IN ('#','**','+','-')) THEN 'INVALID'
         ELSE 'VALID' END AdmissionSourceCode1X,
		 
--  SERVICE LINE CHARGE AMOUNT
--  DI
    CASE WHEN Claim_Type IN ('L','I','O','M','D') 
	AND SvcLineChargeAmt IS NOT NULL
    AND SvcLineChargeAmt >= 0 
        THEN 1 ELSE 0 END SvcLineChargeAmt1,

--  Ex
    CASE WHEN Claim_Type NOT IN ('L','I','O','M','D') THEN 'NOT IN L,I,O,M,D'
	     WHEN SvcLineChargeAmt IS NULL THEN 'NULL'
         WHEN SvcLineChargeAmt < 0 THEN 'INVALID'
         ELSE 'VALID' END SvcLineChargeAmt1X,

--  SERVICE LINE REVENUE CODE
--  DI
    CASE WHEN Claim_Type IN ('L','I','O','M','D') 
	AND SvcLineRevenueCode IS NOT NULL
    AND SvcLineRevenueCode IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_REVENUE' AND CDE_CHAR NOT IN ('#','**','+','-'))
	AND SvcLineAdjRevenueCode IS NOT NULL
    AND SvcLineAdjRevenueCode IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_REVENUE' AND CDE_CHAR NOT IN ('#','**','+','-'))
        THEN 1 ELSE 0 END SvcLineRevenueCode1,

-- Ex
    CASE WHEN Claim_Type NOT IN ('L','I','O','M','D') THEN 'NOT IN L,I,O,M,D'
	     WHEN SvcLineRevenueCode IS NULL OR SvcLineAdjRevenueCode IS NULL THEN 'NULL'
         WHEN SvcLineRevenueCode NOT IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_REVENUE' AND CDE_CHAR NOT IN ('#','**','+','-'))
         OR   SvcLineAdjRevenueCode NOT IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_REVENUE' AND CDE_CHAR NOT IN ('#','**','+','-')) THEN 'INVALID'
         ELSE 'VALID' END SvcLineRevenueCode1X,

-- PATIENT STATUS CODE
--  DI
    CASE WHEN Claim_Type IN ('L','I','O') 
	AND PatientStatusCode IS NOT NULL
    AND PatientStatusCode IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_PATIENT_STATUS' AND CDE_CHAR NOT IN ('#','**','+','-'))
        THEN 1 ELSE 0 END PatientStatusCode1,

--  Ex
    CASE WHEN Claim_Type NOT IN ('L','I','O') THEN 'NOT INPATIENT, LTC or OUTPATIENT'
	     WHEN PatientStatusCode IS NULL THEN 'NULL'
         WHEN PatientStatusCode NOT IN (SELECT CDE_CHAR FROM MHDWDEV.NW.NW_SUP_CODE_REF WHERE CDE_GROUP = 'CDE_PATIENT_STATUS' AND CDE_CHAR NOT IN ('#','**','+','-')) THEN 'INVALID'
         ELSE 'VALID' END PatientStatusCode1X,

--  ALL RECORDS
    1 AS TOT_REX

FROM (
select * from (
select DISTINCT
h."TransSetControlNum" as TransSetControlNum,
h."ImplementationConventionRef" as ImplementationConventionRef,
h."FileName" as FileName,
h."SubmitterID" as SubmitterID,
h."PatientControlNum" as PatientControlNum,
to_number(d."NumDtl",4,0) as NumDtl,
'I' as Claim_Type,
--to_date(d."ServiceDTP",'YYYYMMDD') as DOS_FROM_DATE,
to_date(substr(h."StatementDTP",1,8),'YYYYMMDD') as DOS_FROM_DATE,

h."ClaimFrequencyCode" as ClaimFrequencyCode,
h."AdmissionDTP" as AdmissionDTP,
h."StatementDTP" as StatementDTP,

to_number(d."SvcLineChargeAmt", 12,2) as SvcLineChargeAmt,
a."AdjReasonCode01" as AdjReasonCode01,

h."BillingProvNPI" as BillingProvNPI,

dia."DiagnosisCode" as AdmittingDiagnosisCode,

h."FacilityTypeCode" as FacilityTypeCode,
h."AdmissionTypeCode" as AdmissionTypeCode,
h."AdmissionSourceCode" as AdmissionSourceCode,

dia."DiagnosisCodeQual" as DiagnosisCodeQual,
CASE WHEN LEFT(d."SvcLineRevenueCode",1) != '0' then d."SvcLineRevenueCode" ELSE SUBSTR(d."SvcLineRevenueCode",2,3) END as SvcLineRevenueCode,
CASE WHEN LEFT(a."SvcLineAdjRevenueCode",1) != '0' then a."SvcLineAdjRevenueCode" ELSE SUBSTR(a."SvcLineAdjRevenueCode",2,3) END as SvcLineAdjRevenueCode,

h."PatientStatusCode" as PatientStatusCode

from MHDWDEV.SENDPRO.RAW_SPRO_837I_CLAIM as h

left join MHDWDEV.SENDPRO.RAW_SPRO_837I_CLAIM_SERVICE_LINE_DETAIL as d
on  h."TransSetControlNum" = d."TransSetControlNum"
and h."SubmitterID"        = d."SubmitterID"
and h."PatientControlNum"  = d."PatientControlNum"

left join MHDWDEV.SENDPRO.RAW_SPRO_837I_CLAIM_SVCLN_LINEADJ_INFO as a
on  h."TransSetControlNum" = a."TransSetControlNum"
and h."SubmitterID"        = a."SubmitterID"
and h."PatientControlNum"  = a."PatientControlNum"
and d."NumDtl"             = a."NumDtl"

left join MHDWDEV.SENDPRO.RAW_SPRO_837I_CLAIM_DIAGNOSIS_DTL dia
on  h."TransSetControlNum" = dia."TransSetControlNum"
and h."SubmitterID"        = dia."SubmitterID"
and h."PatientControlNum"  = dia."PatientControlNum"
and dia."DiagnosisCodeQual" = 'ABJ'
order by
    TransSetControlNum,
    ImplementationConventionRef,
    h."SubmitterID",
    h."PatientControlNum",
    to_number(d."NumDtl",4,0)
));
