--DROP VIEW INF_SENDPRO_RAW_RUN_DATE;

CREATE VIEW INF_SENDPRO_RAW_RUN_DATE
AS
    SELECT MAX(MAX_RUN_DATE) AS RUN_DATE
    FROM (
        SELECT MAX(RUN_DATE) AS MAX_RUN_DATE
        FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA
    UNION
        SELECT MAX(RUN_DATE) AS MAX_RUN_DATE
        FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7M_QA
    UNION
        SELECT MAX(RUN_DATE) AS MAX_RUN_DATE
        FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7D_QA
    UNION
        SELECT MAX(RUN_DATE) AS MAX_RUN_DATE
        FROM MHTEAM.DWDQ.INF_B_SENDPRO_NCPDP_DQ_7_QA
    );

SELECT RUN_DATE FROM INF_SENDPRO_RAW_RUN_DATE;

