-- or use DATE RUN table

DROP VIEW INF_SENDPRO_RAW_RUN_DATE;

CREATE VIEW INF_SENDPRO_RAW_RUN_DATE
AS
SELECT RUN_DATE 
FROM MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN;


TRUNCATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN;

SELECT * FROM MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN;

INSERT INTO MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN
SELECT CURRENT_DATE() AS RUN_DATE;

CREATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN
AS
SELECT CURRENT_DATE() AS RUN_DATE;

-- in Informatica
UPDATE MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN
SET RUN_DATE = (SELECT CURRENT_DATE());

-- test

UPDATE MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN
SET RUN_DATE = (SELECT MIN(RUN_DATE) FROM INF_B_SENDPRO_CLAIMS_DQ_7_QA);
-- 2025-08-05

-- this may be used for showing last data in tables
--DROP VIEW INF_SENDPRO_RAW_RUN_DATE;

/*
CREATE VIEW INF_SENDPRO_RAW_RUN_DATE
AS
    SELECT MAX(MAX_RUN_DATE) AS RUN_DATE
    FROM (
        SELECT MAX(RUN_DATE) AS MAX_RUN_DATE
        FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA
    UNION
        SELECT MAX(RUN_DATE) AS MAX_RUN_DATE
        FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7M_QA
    UNION
        SELECT MAX(RUN_DATE) AS MAX_RUN_DATE
        FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7D_QA
    UNION
        SELECT MAX(RUN_DATE) AS MAX_RUN_DATE
        FROM MHTEAM.DWDQ.INF_B_SENDPRO_NCPDP_DQ_7_QA
    );

SELECT RUN_DATE FROM INF_SENDPRO_RAW_RUN_DATE;
*/

