-- or use DATE RUN table

DROP VIEW INF_SENDPRO_TARGET_RUN_DATE;

CREATE VIEW INF_SENDPRO_TARGET_RUN_DATE
AS
SELECT RUN_DATE 
FROM MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN;

SELECT * FROM MHTEAM.DWDQ.INF_SENDPRO_TARGET_RUN_DATE;

TRUNCATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_TARGET_DATE_RUN;

SELECT * FROM MHTEAM.DWDQ.INF_B_SENDPRO_TARGET_DATE_RUN;

INSERT INTO MHTEAM.DWDQ.INF_B_SENDPRO_TARGET_DATE_RUN
SELECT CURRENT_DATE() AS RUN_DATE;

CREATE TABLE MHTEAM.DWDQ.INF_B_SENDPRO_TARGET_DATE_RUN
AS
SELECT CURRENT_DATE() AS RUN_DATE;

-- in Informatica
UPDATE MHTEAM.DWDQ.INF_B_SENDPRO_TARGET_DATE_RUN
SET RUN_DATE = (SELECT CURRENT_DATE());

