SELECT * -- COUNT(1)
FROM (
SELECT 
	UP.RUN_DATE,
	UP.FILENAME,
	UP.CLAIM_TYPE,
	UP.RECORD_TYPE,
	UP.MEASURE,
	UP.TYPE,
	UP.REC_CNT,
	UP.SUBMITTERNAME,
    L.BENCHMARK
FROM INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV UP
LEFT JOIN INF_B_SENDPRO_LOOKUP L ON UP.MEASURE = L.BENCHMARK
)
WHERE BENCHMARK IS NULL;

select * 
from INF_B_SENDPRO_LOOKUP 
order by BENCHMARK;

SELECT COUNT(1)
--SELECT * 
FROM INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;
-- 8702

--------------------

select * 
from MHTEAM.DWDQ.INF_B_SC_STG_MCO_MBH_SCORECARD_LOOKUP
where BENCHMARK_THRESHOLD < 1.0
order by BENCHMARK;

select * 
from MHTEAM.DWDQ.INF_B_SC_STG_OC_SCORECARD_LOOKUP
where BENCHMARK_THRESHOLD < 1.0
order by BENCHMARK;


select * 
from INF_B_SENDPRO_LOOKUP 
order by BENCHMARK;

drop table INF_B_SENDPRO_LOOKUP;

create table INF_B_SENDPRO_LOOKUP
(
BENCHMARK              varchar(100),
BENCHMARK_THRESHOLD    number(3,2)
);

select 'insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES (''' || measure || ''', 1.0);'  
from (
select distinct measure
from MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
)
order by measure;

select 'update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = ''' || measure || ''' ;'  
from (
select distinct measure
from MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
)
order by measure;

--truncate table INF_B_SENDPRO_LOOKUP;

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_SOURCE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMITTING_DIAGNOSIS_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILL_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILL_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILL_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CDT_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CLAIM_FREQUENCY_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CONDITION_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CPT_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('FACILITY_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('HIPPS_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ICD10_DIAG_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OCCURENCE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OCCURRENCE_SPAN_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OPERATING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OPERATING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OPERATING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OTHER_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OTHER_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OTHER_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PATIENT_STATUS_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRINCIPAL_DIAG_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PROCEDURE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('RENDERING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('RENDERING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('RENDERING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_ADJUST_REVENUE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_ADJ_PROC_MOD', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_CHRG_AMT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_PROC_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_PROC_MOD', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_REVENUE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('STATEMENT_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('VALUE_CODE', 1.0);


update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.98 where BENCHMARK = 'ATTENDING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ATTENDING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OPERATING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OTHER_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.98 where BENCHMARK = 'PATIENT_STATUS_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'PROCEDURE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'REFERRING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'RENDERING_PROVIDER_NPI' ;

-- 837P

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ORDERING_PROVIDER_INTERNAL_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ORDERING_PROVIDER_NPI', 0.99);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ORDERING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SUPERVISING_PROVIDER_INTERNAL_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SUPERVISING_PROVIDER_NPI', 0.99);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SUPERVISING_PROVIDER_PIDSL', 1.0);

-- 837D

--delete from INF_B_SENDPRO_LOOKUP where BENCHMARK = 'ASSISTANT_SURG_ORDERING_PROVIDER_NPI';
--delete from INF_B_SENDPRO_LOOKUP where BENCHMARK = 'ASSISTANT_SURG_ORDERING_PROVIDER_PIDSL';

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ASSISTANT_SURG_PROVIDER_INTERNAL_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ASSISTANT_SURG_PROVIDER_NPI', 0.99);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ASSISTANT_SURG_PROVIDER_PIDSL', 1.0);

-- 837_NCPDP

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADJUDICATION_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CARDHOLDER_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('COMPOUND_NDC', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('NDC', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBER_PROVIDER_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBER_PROVIDER_NPI', 0.99);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_PROVIDER_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_PROVIDER_NPI', 0.99);

-- Target additions

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ALLOWED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILL_PROVIDER_TAXONOMY', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CLAIM_CONTRACT_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DISCHARGE_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('FACILITY_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('MEMBER_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PAID_AMOUNT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PLACE_OF_SERVICE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PROCEDURE_MOD_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('QUANTITY_BILLED', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_LOCATION', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_TAXONOMY', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_TYPE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('TO_SERVICE_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ALLOWED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DISPENSE_AS_WRITTEN', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DISPENSE_FEE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DISPENSE_QUANTITY', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('NDC', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBER_PROVIDER_LOCATION', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIPTION_NUMBER', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIPTION_ORIGIN', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('RECORD_STATUS', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFILL_INDICATOR', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SCRIPT_WRITTEN_DATE', 1.0);


--------------

update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ADMISSION_DATE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ADMISSION_SOURCE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ADMISSION_TYPE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ADMITTING_DIAGNOSIS_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ATTENDING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ATTENDING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ATTENDING_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'CDT_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'CLAIM_FREQUENCY_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'CONDITION_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'CPT_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'FACILITY_TYPE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'HIPPS_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ICD10_DIAG_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OCCURENCE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OCCURRENCE_SPAN_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OPERATING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OPERATING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OPERATING_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OTHER_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OTHER_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OTHER_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'PATIENT_STATUS_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'PRINCIPAL_DIAG_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'PROCEDURE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'REFERRING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'REFERRING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'REFERRING_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'RENDERING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'RENDERING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'RENDERING_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_ADJUST_REVENUE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_PROC_MOD' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_CHRG_AMT' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_PROC_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_PROC_MOD' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_REVENUE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'STATEMENT_DATE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'VALUE_CODE' ;

-- Target additions 10/31/2025

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRICING_METHOD_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('TOOTH_NUMBER', 1.0);


UPDATE INF_B_SENDPRO_LOOKUP SET BENCHMARK = 'BILLING_PROVIDER_INTERNAL_ADDRESS_LOCATION' WHERE BENCHMARK = 'BILLING_PROVIDER_PIDSL';
UPDATE INF_B_SENDPRO_LOOKUP SET BENCHMARK = 'SERVICING_PROVIDER_INTERNAL_ADDRESS_LOCATION' WHERE BENCHMARK = 'SERVICING_PROVIDER_PIDSL';

-- Adding BILLING bechmarks until change RAW

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_TAXONOMY', 1.0);


-- Target additions 12/22/2025

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_LOCATION', 1.0);

delete from INF_B_SENDPRO_LOOKUP where BENCHMARK = 'SERVICE_LINE_REVENUE_COD';
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_CATEGORY_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_REV_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ORAL_CATEGORY_DESC', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('TOOTH_SURFACE_CODE', 1.0);

-- Target additions 3/13/2026

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBER_PROVIDER_INTERNAL_ADDRESS_LOCATION', 1.0);

-- Target additions 8/26/2026

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DIAGNOSIS_RELATED_GROUP', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADJ_DIAGNOSIS_RELATED_GROUP', 1.0);
