DROP VIEW INF_B_SENDPRO_CLAIMS_DQ_7D_QA_UNPIV;

SELECT * FROM INF_B_SENDPRO_CLAIMS_DQ_7D_QA_UNPIV;

SELECT * 
FROM INF_B_SENDPRO_CLAIMS_DQ_7D_QA_UNPIV
ORDER BY FILENAME, CLAIM_TYPE, MEASURE;

SELECT DISTINCT filename
FROM INF_B_SENDPRO_CLAIMS_DQ_7D_QA_UNPIV;


SELECT *
FROM INF_B_SENDPRO_CLAIMS_DQ_7D_QA_UNPIV
--where MEASURE = 'ADMISSIONDTP1X'
--where FILENAME = '110025617h_pacdri_03032025113026_test_de_e2948853-4667-434e-aefd-d51abc7a2ae0.xml'
where FILENAME = '110031447a_pacdrd_03142025075105_test_pd.edi_a0271ff1-4412-4126-a3b6-e42de1e214fe.xml'
--and TYPE = 'INVALID'
and MEASURE = 'BILL_PROVIDER_PIDSL'
order by FILENAME, CLAIM_TYPE, MEASURE, TYPE


SELECT * 
FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7D_QA

DROP VIEW INF_B_SENDPRO_CLAIMS_DQ_7D_QA_UNPIV;

-- thu 5/15 - first 7
-- wed 7/9 added benchmark

CREATE VIEW INF_B_SENDPRO_CLAIMS_DQ_7D_QA_UNPIV
AS

SELECT DISTINCT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, REC_CNT,
DS."SubmitterLastOrgName" AS SUBMITTERNAME,
L.BENCHMARK_THRESHOLD

FROM
(
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, COUNT(TYPE) AS REC_CNT
FROM (
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    RECORD_TYPE,
    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEADJREVENUECODE1X AS Service_Line_Revenue_Code,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    SUP_SUPERVISINGPROVNPI1X Supervising_Provider_NPI,
    SUP_PROVIDERINTERNALID1X Supervising_Provider_Internal_ID,
    SUP_PROVIDERPIDSL1X Supervising_Provider_PIDSL,

    ASST_ASSISTANTSURGEONPROVNPI1X Assistant_Surg_Provider_NPI,
    ASST_PROVIDERINTERNALID1X Assistant_Surg_Provider_Internal_ID,
    ASST_PROVIDERPIDSL1X Assistant_Surg_Provider_PIDSL

    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7D_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
    
    Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Supervising_Provider_NPI,
    Supervising_Provider_Internal_ID,
    Supervising_Provider_PIDSL,

    Assistant_Surg_Provider_NPI,
    Assistant_Surg_Provider_Internal_ID,
    Assistant_Surg_Provider_PIDSL
)
) AS INF_B_SENDPRO_CLAIMS_DQ_7D_UNPIV
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
)
GROUP BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837D_FILE_STATISTICS DS
    ON A.FILENAME = DS."FileName" AND A.CLAIM_TYPE = 'D'
JOIN INF_B_SENDPRO_LOOKUP L ON A.MEASURE = L.BENCHMARK
ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE;

