SELECT * -- COUNT(1)
FROM (
SELECT 
	UP.RUN_DATE,
	UP.FILENAME,
	UP.CLAIM_TYPE,
	UP.RECORD_TYPE,
	UP.MEASURE,
	UP.TYPE,
	UP.REC_CNT,
	UP.SUBMITTERNAME,
    L.BENCHMARK
FROM INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV UP
LEFT JOIN INF_B_SENDPRO_LOOKUP L ON UP.MEASURE = L.BENCHMARK
)
WHERE BENCHMARK IS NULL;

select * 
from INF_B_SENDPRO_LOOKUP 
order by BENCHMARK;

SELECT COUNT(1)
--SELECT * 
FROM INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;
-- 8702

--------------------

select * 
from MHTEAM.DWDQ.INF_B_SC_STG_MCO_MBH_SCORECARD_LOOKUP
where BENCHMARK_THRESHOLD < 1.0
order by BENCHMARK;

select * 
from MHTEAM.DWDQ.INF_B_SC_STG_OC_SCORECARD_LOOKUP
where BENCHMARK_THRESHOLD < 1.0
order by BENCHMARK;


select * 
from INF_B_SENDPRO_LOOKUP 
order by BENCHMARK;

drop table INF_B_SENDPRO_LOOKUP;

create table INF_B_SENDPRO_LOOKUP
(
BENCHMARK              varchar(100),
BENCHMARK_THRESHOLD    number(3,2)
);

select 'insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES (''' || measure || ''', 1.0);'  
from (
select distinct measure
from MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
)
order by measure;

select 'update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = ''' || measure || ''' ;'  
from (
select distinct measure
from MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
)
order by measure;

--truncate table INF_B_SENDPRO_LOOKUP;

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_SOURCE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMISSION_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADMITTING_DIAGNOSIS_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ATTENDING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILL_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILL_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILL_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CDT_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CLAIM_FREQUENCY_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CONDITION_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CPT_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('FACILITY_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('HIPPS_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ICD10_DIAG_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OCCURENCE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OCCURRENCE_SPAN_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OPERATING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OPERATING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OPERATING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OTHER_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OTHER_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('OTHER_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PATIENT_STATUS_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRINCIPAL_DIAG_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PROCEDURE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFERRING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('RENDERING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('RENDERING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('RENDERING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_ADJUST_REVENUE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_ADJ_PROC_MOD', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_CHRG_AMT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_PROC_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_PROC_MOD', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_LINE_REVENUE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('STATEMENT_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('VALUE_CODE', 1.0);


update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.98 where BENCHMARK = 'ATTENDING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ATTENDING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OPERATING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OTHER_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.98 where BENCHMARK = 'PATIENT_STATUS_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'PROCEDURE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'REFERRING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'RENDERING_PROVIDER_NPI' ;

-- 837P

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ORDERING_PROVIDER_INTERNAL_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ORDERING_PROVIDER_NPI', 0.99);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ORDERING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SUPERVISING_PROVIDER_INTERNAL_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SUPERVISING_PROVIDER_NPI', 0.99);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SUPERVISING_PROVIDER_PIDSL', 1.0);

-- 837D

--delete from INF_B_SENDPRO_LOOKUP where BENCHMARK = 'ASSISTANT_SURG_ORDERING_PROVIDER_NPI';
--delete from INF_B_SENDPRO_LOOKUP where BENCHMARK = 'ASSISTANT_SURG_ORDERING_PROVIDER_PIDSL';

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ASSISTANT_SURG_PROVIDER_INTERNAL_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ASSISTANT_SURG_PROVIDER_NPI', 0.99);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ASSISTANT_SURG_PROVIDER_PIDSL', 1.0);

-- 837_NCPDP

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ADJUDICATION_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CARDHOLDER_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('COMPOUND_NDC', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('NDC', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBER_PROVIDER_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBER_PROVIDER_NPI', 0.99);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_PROVIDER_ID', 0.98);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICE_PROVIDER_NPI', 0.99);

-- Target additions

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ALLOWED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILL_PROVIDER_TAXONOMY', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('CLAIM_CONTRACT_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DISCHARGE_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('FACILITY_TYPE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('MEMBER_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PAID_AMOUNT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PLACE_OF_SERVICE_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PROCEDURE_MOD_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('QUANTITY_BILLED', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_LOCATION', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_TAXONOMY', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_TYPE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('TO_SERVICE_DATE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('ALLOWED_AMOUNT', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DISPENSE_AS_WRITTEN', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DISPENSE_FEE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('DISPENSE_QUANTITY', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('NDC', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIBER_PROVIDER_LOCATION', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIPTION_NUMBER', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRESCRIPTION_ORIGIN', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('RECORD_STATUS', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('REFILL_INDICATOR', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SCRIPT_WRITTEN_DATE', 1.0);


--------------

update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ADMISSION_DATE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ADMISSION_SOURCE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ADMISSION_TYPE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ADMITTING_DIAGNOSIS_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ATTENDING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ATTENDING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ATTENDING_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'BILL_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'CDT_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'CLAIM_FREQUENCY_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'CONDITION_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'CPT_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'FACILITY_TYPE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'HIPPS_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'ICD10_DIAG_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OCCURENCE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OCCURRENCE_SPAN_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OPERATING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OPERATING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OPERATING_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OTHER_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OTHER_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'OTHER_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'PATIENT_STATUS_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'PRINCIPAL_DIAG_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'PROCEDURE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'REFERRING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'REFERRING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'REFERRING_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'RENDERING_PROVIDER_INTERNAL_ID' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'RENDERING_PROVIDER_NPI' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'RENDERING_PROVIDER_PIDSL' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_ADJUST_REVENUE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_PROC_MOD' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_CHRG_AMT' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_PROC_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_PROC_MOD' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'SERVICE_LINE_REVENUE_CODE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'STATEMENT_DATE' ;
update INF_B_SENDPRO_LOOKUP set BENCHMARK_THRESHOLD = 0.99 where BENCHMARK = 'VALUE_CODE' ;

-- Target additions 10/31/2025

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('SERVICING_PROVIDER_PIDSL', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('PRICING_METHOD_CODE', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('TOOTH_NUMBER', 1.0);

-- Adding BILLING bechmarks until change RAW

insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_INTERNAL_ID', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_NPI', 1.0);
insert into INF_B_SENDPRO_LOOKUP ( BENCHMARK, BENCHMARK_THRESHOLD ) VALUES ('BILLING_PROVIDER_TAXONOMY', 1.0);

/*
create or replace view MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA_UNPIV(
	RUN_DATE,
	FILENAME,
	CLAIM_TYPE,
	RECORD_TYPE,
	MEASURE,
	TYPE,
	REC_CNT,
	SUBMITTERNAME
) as

SELECT DISTINCT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, REC_CNT,
CASE WHEN A.CLAIM_TYPE = 'M' THEN PS."SubmitterLastOrgName"
     WHEN A.CLAIM_TYPE = 'D' THEN DS."SubmitterLastOrgName"
     ELSE S."SubmitterLastOrgName"
END AS SUBMITTERNAME
FROM
(
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, COUNT(TYPE) AS REC_CNT
FROM (
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    RECORD_TYPE,

    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	STATEMENTDTP1X AS Statement_Date,
	ADMISSIONDTP1X AS Admission_Date,
	ADMITTINGDIAGNOSISCODE1X AS Admitting_Diagnosis_Code,
	FACILITYTYPECODE1X AS Facility_Type_Code,
	ADMISSIONTYPECODE1X AS Admission_Type_Code,
	ADMISSIONSOURCECODE1X AS Admission_Source_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEREVENUECODE1X AS Service_Line_Revenue_Code,
	OCCURRENCECODE1X AS Occurence_Code,
	OCCURRENCESPANCODE1X AS Occurrence_Span_Code,
	VALUECODE1X AS Value_Code,
	CONDITIONCODE1X AS Condition_Code,
	PATIENTSTATUSCODE1X AS Patient_Status_Code,
	PRINCIPALDIAGNOSISCODE1X AS Principal_Diag_Code,
	ICD10DIAGNOSIS_CODE1X AS ICD10_Diag_Code,
	MULTIPLEPROCEDURECODE1X AS Service_Line_Proc_Code,
	CDT_CODE1X AS CDT_Code,
	CPT_CODE1X AS CPT_Code,
	HIPPS_CODE1X AS HIPPS_Code,
	SVCLINEPROCMOD1X AS Service_Line_Proc_Mod,
	SVCLINEADJREVENUECODE1X AS Service_Line_Adjust_Revenue_Code,
	PROCEDURECODE1X AS Procedure_Code,
	SVCLINEADJUDICATIONPROCMOD1X AS Service_Line_Adj_Revenue_Code,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    AT_ATTENDINGPROVNPI1X Attending_Provider_NPI,
    AT_PROVIDERINTERNALID1X Attending_Provider_Internal_ID,
    AT_PROVIDERPIDSL1X Attending_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    OOP_OTHEROPERPROVNPI1X Other_Provider_NPI,
    OOP_PROVIDERINTERNALID1X Other_Provider_Internal_ID,
    OOP_PROVIDERPIDSL1X Other_Provider_PIDSL,

    OP_OPERATINGPROVNPI1X Operating_Provider_NPI,
    OP_PROVIDERINTERNALID1X Operating_Provider_Internal_ID,
    OP_PROVIDERPIDSL1X Operating_Provider_PIDSL


    
    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Statement_Date,
	Admission_Date,
	Admitting_Diagnosis_Code,
	Facility_Type_Code,
	Admission_Type_Code,
	Admission_Source_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
	Occurence_Code,
	Occurrence_Span_Code,
	Value_Code,
	Condition_Code,
	Patient_Status_Code,
	Principal_Diag_Code,
	ICD10_Diag_Code,
	Service_Line_Proc_Code,
	CDT_Code,
	CPT_Code,
	HIPPS_Code,
	Service_Line_Proc_Mod,
	Service_Line_Adjust_Revenue_Code,
	Procedure_Code,
	Service_Line_Adj_Revenue_Code,
    
	Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Attending_Provider_NPI,
    Attending_Provider_Internal_ID,
    Attending_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Other_Provider_NPI,
    Other_Provider_Internal_ID,
    Other_Provider_PIDSL,

    Operating_Provider_NPI,
    Operating_Provider_Internal_ID,
    Operating_Provider_PIDSL
)
) AS INF_B_SENDPRO_CLAIMS_DQ_7_UNPIV
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
)
GROUP BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837I_FILE_STATISTICS S
    ON A.FILENAME = S."FileName" AND A.CLAIM_TYPE IN ('I','L','O')
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837P_FILE_STATISTICS PS
    ON A.FILENAME = PS."FileName" AND A.CLAIM_TYPE = 'M'
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837D_FILE_STATISTICS DS
    ON A.FILENAME = DS."FileName" AND A.CLAIM_TYPE = 'D'    
ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE;
*/