create or replace view MHTEAM.DWDQ.INF_SENDPRO_NCPDP_DQ_QA_7_UNPIV(
	RUN_DATE,
	FILENAME,
	CLAIM_TYPE,
	MEASURE,
	PAHDRSENDINGENTITYID,
	TYPE,
	REC_CNT,
	BENCHMARK_THRESHOLD
) as

SELECT DISTINCT RUN_DATE, FILENAME, CLAIM_TYPE, MEASURE, PAHdrSendingEntityID, TYPE, REC_CNT,
L.BENCHMARK_THRESHOLD
FROM (
SELECT DISTINCT RUN_DATE, FILENAME, CLAIM_TYPE, MEASURE, PAHdrSendingEntityID, TYPE, COUNT(TYPE) AS REC_CNT
FROM (
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, PAHdrSendingEntityID, MEASURE, TYPE
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    PAHdrSendingEntityID,
	SUBSCRIBERMEMBERID1X AS Cardholder_Id,
	NDCSERV1X            AS NDC,
	COMPNDPRODCODE1X     AS Compound_NDC,
	ADJUDICATIONDATE1X   AS Adjudication_Date, 
	SERVPROVNPI1X        AS Service_Provider_NPI,
	SERVPROVSECID1X      AS Service_Provider_ID,
    PRESCRIBERNPI1X      AS Prescriber_Provider_NPI,
    PRESCRIBERSECID1X    AS Prescriber_Provider_ID
    
    FROM MHTEAM.DWDQ.INF_SENDPRO_NCPDP_DQ_QA_7_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Cardholder_Id,
	NDC,
	Compound_NDC,
	Adjudication_Date, 
	Service_Provider_NPI,
	Service_Provider_ID,
    Prescriber_Provider_NPI,
    Prescriber_Provider_ID
)
) AS INF_SENDPRO_NCPDP_DQ_QA_7_UNPIV
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, MEASURE, TYPE
)
GROUP BY RUN_DATE, FILENAME, CLAIM_TYPE, PAHdrSendingEntityID, MEASURE, TYPE
) A
JOIN INF_B_SENDPRO_LOOKUP L ON A.MEASURE = L.BENCHMARK
ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE;
