--DROP VIEW INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;

SELECT * FROM INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;

SELECT * 
FROM INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
ORDER BY FILENAME, CLAIM_TYPE, MEASURE
LIMIT 10;


SELECT MEASURE, SUM(VALID) SUM_VALID, SUM(TOT_REC) SUM_TOT_REC
FROM (
SELECT *,
CASE WHEN TYPE = 'VALID' OR TYPE = 'NOT APP' THEN 1 
     WHEN TYPE = 'INVALID' OR TYPE = 'NULL' THEN 0
     ELSE 0
     END VALID,
     1 TOT_REC

FROM INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
WHERE CLAIM_TYPE = 'O'
AND RECORD_TYPE = 'O'
AND FILENAME = '110025617d_pacdri_05092025012200_test_pd_d654ab34-0de5-4bee-b22d-0bf88255f71b.xml'
ORDER BY FILENAME, CLAIM_TYPE, MEASURE
)
GROUP BY MEASURE
ORDER BY MEASURE
LIMIT 10;



SELECT DISTINCT FILENAME 
FROM INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;

SELECT * 
FROM INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
--where MEASURE = 'ADMISSIONDTP1X'
where FILENAME = '110025617h_pacdri_14032025082720_test_pd_5aecdb7e-5688-4d68-ae2d-aa596c911f26.xml'
order by FILENAME, CLAIM_TYPE, MEASURE, TYPE


SELECT * 
FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7_QA

GRANT SELECT ON MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV TO DI_TEAM_ROLE;

DROP VIEW INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;

-- tue 5/13 - first 7
-- mon 3/24 - lastest one
-- thu 4/3 = latest one

select * from INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;

select count(1) from INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;

select sum(REC_CNT)
from INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
where --filename = '110025617d_pacdrp_05092025013247_test_fd_4cab7bd7-492b-4fc0-ab42-d3afe3c464fb.xml' and 
measure = 'CPT_CODE';

DROP VIEW INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV;

CREATE VIEW INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
AS

SELECT DISTINCT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, REC_CNT,
S."SubmitterLastOrgName" AS SUBMITTERNAME,
L.BENCHMARK_THRESHOLD
FROM
(
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, COUNT(TYPE) AS REC_CNT
FROM (
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    RECORD_TYPE,
    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	STATEMENTDTP1X AS Statement_Date,
	ADMISSIONDTP1X AS Admission_Date,
	ADMITTINGDIAGNOSISCODE1X AS Admitting_Diagnosis_Code,
	FACILITYTYPECODE1X AS Facility_Type_Code,
	ADMISSIONTYPECODE1X AS Admission_Type_Code,
	ADMISSIONSOURCECODE1X AS Admission_Source_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEREVENUECODE1X AS Service_Line_Revenue_Code,
	OCCURRENCECODE1X AS Occurence_Code,
	OCCURRENCESPANCODE1X AS Occurrence_Span_Code,
	VALUECODE1X AS Value_Code,
	CONDITIONCODE1X AS Condition_Code,
	PATIENTSTATUSCODE1X AS Patient_Status_Code,
	PRINCIPALDIAGNOSISCODE1X AS Principal_Diag_Code,
	ICD10DIAGNOSIS_CODE1X AS ICD10_Diag_Code,
	MULTIPLEPROCEDURECODE1X AS Service_Line_Proc_Code,
	CDT_CODE1X AS CDT_Code,
	CPT_CODE1X AS CPT_Code,
	HIPPS_CODE1X AS HIPPS_Code,
	SVCLINEPROCMOD1X AS Service_Line_Proc_Mod,
	SVCLINEADJREVENUECODE1X AS Service_Line_Adjust_Revenue_Code,
	PROCEDURECODE1X AS Procedure_Code,
	SVCLINEADJUDICATIONPROCMOD1X AS Service_Line_Adj_Proc_Mod,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    AT_ATTENDINGPROVNPI1X Attending_Provider_NPI,
    AT_PROVIDERINTERNALID1X Attending_Provider_Internal_ID,
    AT_PROVIDERPIDSL1X Attending_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    OOP_OTHEROPERPROVNPI1X Other_Provider_NPI,
    OOP_PROVIDERINTERNALID1X Other_Provider_Internal_ID,
    OOP_PROVIDERPIDSL1X Other_Provider_PIDSL,

    OP_OPERATINGPROVNPI1X Operating_Provider_NPI,
    OP_PROVIDERINTERNALID1X Operating_Provider_Internal_ID,
    OP_PROVIDERPIDSL1X Operating_Provider_PIDSL
    
    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Statement_Date,
	Admission_Date,
	Admitting_Diagnosis_Code,
	Facility_Type_Code,
	Admission_Type_Code,
	Admission_Source_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
	Occurence_Code,
	Occurrence_Span_Code,
	Value_Code,
	Condition_Code,
	Patient_Status_Code,
	Principal_Diag_Code,
	ICD10_Diag_Code,
	Service_Line_Proc_Code,
	CDT_Code,
	CPT_Code,
	HIPPS_Code,
	Service_Line_Proc_Mod,
	Service_Line_Adjust_Revenue_Code,
	Procedure_Code,
	Service_Line_Adj_Proc_Mod,
    
	Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Attending_Provider_NPI,
    Attending_Provider_Internal_ID,
    Attending_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Other_Provider_NPI,
    Other_Provider_Internal_ID,
    Other_Provider_PIDSL,

    Operating_Provider_NPI,
    Operating_Provider_Internal_ID,
    Operating_Provider_PIDSL
)
) AS INF_SENDPRO_CLAIMS_DQ_7_UNPIV
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
)
GROUP BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837I_FILE_STATISTICS S
    ON A.FILENAME = S."FileName" AND A.CLAIM_TYPE IN ('I','L','O')
JOIN INF_B_SENDPRO_LOOKUP L ON A.MEASURE = L.BENCHMARK

ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE;

-------------------

SELECT * FROM (
SELECT FILENAME, CLAIM_TYPE, MEASURE, TYPE, REC_CNT
FROM INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV
ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE
)
MINUS
SELECT * FROM (
SELECT FILENAME, CLAIM_TYPE, MEASURE, TYPE, REC_CNT
FROM INF_B_SENDPRO_CLAIMS_DQ_7_QA_PIV
ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE
)
;

