create or replace view MHTEAM.DWDQ.INF_SENDPRO_RAW_RUN_DATE(
	RUN_DATE
) as
SELECT RUN_DATE 
FROM MHTEAM.DWDQ.INF_B_SENDPRO_DATE_RUN;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	FILENAME,
	PATIENTCONTROLNUM,
	NUMDTL,
	CLAIM_TYPE,
	RECORD_TYPE,
	CLAIMFREQUENCYCODE1X,
	STATEMENTDTP1X,
	ADMISSIONDTP1X,
	ADMITTINGDIAGNOSISCODE1X,
	FACILITYTYPECODE1X,
	ADMISSIONTYPECODE1X,
	ADMISSIONSOURCECODE1X,
	SVCLINECHARGEAMT1X,
	SVCLINEREVENUECODE1X,
	OCCURRENCECODE1X,
	OCCURRENCESPANCODE1X,
	VALUECODE1X,
	CONDITIONCODE1X,
	PATIENTSTATUSCODE1X,
	PRINCIPALDIAGNOSISCODE1X,
	ICD10DIAGNOSIS_CODE1X,
	MULTIPLEPROCEDURECODE1X,
	CDT_CODE1X,
	CPT_CODE1X,
	HIPPS_CODE1X,
	SVCLINEPROCMOD1X,
	SVCLINEADJREVENUECODE1X,
	PROCEDURECODE1X,
	SVCLINEADJUDICATIONPROCMOD1X,
	BILLINGPROVNPI1X,
	BILL_PROVIDERINTERNALID1X,
	BILL_PROVIDERPIDSL1X,
	AT_ATTENDINGPROVNPI1X,
	AT_PROVIDERINTERNALID1X,
	AT_PROVIDERPIDSL1X,
	REF_REFERRINGPROVNPI1X,
	REF_PROVIDERINTERNALID1X,
	REF_PROVIDERPIDSL1X,
	REN_RENDERINGPROVNPI1X,
	REN_PROVIDERINTERNALID1X,
	REN_PROVIDERPIDSL1X,
	OOP_OTHEROPERPROVNPI1X,
	OOP_PROVIDERINTERNALID1X,
	OOP_PROVIDERPIDSL1X,
	OP_OPERATINGPROVNPI1X,
	OP_PROVIDERINTERNALID1X,
	OP_PROVIDERPIDSL1X,
	TOT_REX
) as
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
FILENAME,
PATIENTCONTROLNUM,
NUMDTL,
CLAIM_TYPE,
RECORD_TYPE,
CLAIMFREQUENCYCODE1X,
STATEMENTDTP1X,
ADMISSIONDTP1X,
ADMITTINGDIAGNOSISCODE1X,
FACILITYTYPECODE1X,
ADMISSIONTYPECODE1X,
ADMISSIONSOURCECODE1X,
SVCLINECHARGEAMT1X,
SVCLINEREVENUECODE1X,
OCCURRENCECODE1X,
OCCURRENCESPANCODE1X,
VALUECODE1X,
CONDITIONCODE1X,
PATIENTSTATUSCODE1X,
PRINCIPALDIAGNOSISCODE1X,
ICD10DIAGNOSIS_CODE1X,
MULTIPLEPROCEDURECODE1X,
CDT_CODE1X,
CPT_CODE1X,
HIPPS_CODE1X,
SVCLINEPROCMOD1X,
SVCLINEADJREVENUECODE1X,
PROCEDURECODE1X,
SVCLINEADJUDICATIONPROCMOD1X,

BILLINGPROVNPI1X,
BILL_PROVIDERINTERNALID1X,
BILL_PROVIDERPIDSL1X,

AT_ATTENDINGPROVNPI1X,
AT_PROVIDERINTERNALID1X,
AT_PROVIDERPIDSL1X,

REF_REFERRINGPROVNPI1X,
REF_PROVIDERINTERNALID1X,
REF_PROVIDERPIDSL1X,

REN_RENDERINGPROVNPI1X,
REN_PROVIDERINTERNALID1X,
REN_PROVIDERPIDSL1X,

OOP_OTHEROPERPROVNPI1X,
OOP_PROVIDERINTERNALID1X,
OOP_PROVIDERPIDSL1X,

OP_OPERATINGPROVNPI1X,
OP_PROVIDERINTERNALID1X,
OP_PROVIDERPIDSL1X,

TOT_REX
FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_7_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	FILENAME,
	PATIENTCONTROLNUM,
	NUMDTL,
	CLAIM_TYPE,
	RECORD_TYPE,
	CLAIMFREQUENCYCODE1,
	STATEMENTDTP1,
	ADMISSIONDTP1,
	ADMITTINGDIAGNOSISCODE1,
	FACILITYTYPECODE1,
	ADMISSIONTYPECODE1,
	ADMISSIONSOURCECODE1,
	SVCLINECHARGEAMT1,
	SVCLINEREVENUECODE1,
	OCCURRENCECODE1,
	OCCURRENCESPANCODE1,
	VALUECODE1,
	CONDITIONCODE1,
	PATIENTSTATUSCODE1,
	PRINCIPALDIAGNOSISCODE1,
	ICD10DIAGNOSIS_CODE1,
	MULTIPLEPROCEDURECODE1,
	CDT_CODE1,
	CPT_CODE1,
	HIPPS_CODE1,
	SVCLINEPROCMOD1,
	SVCLINEADJREVENUECODE1,
	PROCEDURECODE1,
	SVCLINEADJUDICATIONPROCMOD1,
	BILLINGPROVNPI1,
	BILL_PROVIDERINTERNALID1,
	BILL_PROVIDERPIDSL1,
	AT_ATTENDINGPROVNPI1,
	AT_PROVIDERINTERNALID1,
	AT_PROVIDERPIDSL1,
	REF_REFERRINGPROVNPI1,
	REF_PROVIDERINTERNALID1,
	REF_PROVIDERPIDSL1,
	REN_RENDERINGPROVNPI1,
	REN_PROVIDERINTERNALID1,
	REN_PROVIDERPIDSL1,
	OOP_OTHEROPERPROVNPI1,
	OOP_PROVIDERINTERNALID1,
	OOP_PROVIDERPIDSL1,
	OP_OPERATINGPROVNPI1,
	OP_PROVIDERINTERNALID1,
	OP_PROVIDERPIDSL1,
	TOT_REX
) as
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
FILENAME,
PATIENTCONTROLNUM,
NUMDTL,
CLAIM_TYPE,
RECORD_TYPE,
CLAIMFREQUENCYCODE1,
STATEMENTDTP1,
ADMISSIONDTP1,
ADMITTINGDIAGNOSISCODE1,
FACILITYTYPECODE1,
ADMISSIONTYPECODE1,
ADMISSIONSOURCECODE1,
SVCLINECHARGEAMT1,
SVCLINEREVENUECODE1,
OCCURRENCECODE1,
OCCURRENCESPANCODE1,
VALUECODE1,
CONDITIONCODE1,
PATIENTSTATUSCODE1,
PRINCIPALDIAGNOSISCODE1,
ICD10DIAGNOSIS_CODE1,
MULTIPLEPROCEDURECODE1,
CDT_CODE1,
CPT_CODE1,
HIPPS_CODE1,
SVCLINEPROCMOD1,
SVCLINEADJREVENUECODE1,
PROCEDURECODE1,
SVCLINEADJUDICATIONPROCMOD1,

BILLINGPROVNPI1,
BILL_PROVIDERINTERNALID1,
BILL_PROVIDERPIDSL1,

AT_ATTENDINGPROVNPI1,
AT_PROVIDERINTERNALID1,
AT_PROVIDERPIDSL1,

REF_REFERRINGPROVNPI1,
REF_PROVIDERINTERNALID1,
REF_PROVIDERPIDSL1,

REN_RENDERINGPROVNPI1,
REN_PROVIDERINTERNALID1,
REN_PROVIDERPIDSL1,

OOP_OTHEROPERPROVNPI1,
OOP_PROVIDERINTERNALID1,
OOP_PROVIDERPIDSL1,

OP_OPERATINGPROVNPI1,
OP_PROVIDERINTERNALID1,
OP_PROVIDERPIDSL1,

TOT_REX
FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7_QA;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_STATS_7_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	SUBMITTERNAME,
	CLAIM_TYPE,
	FILENAME,
	RECORD_TYPE,
	PCT_CLAIMFREQUENCYCODE1,
	PCT_STATEMENTDTP1,
	PCT_ADMISSIONDTP1,
	PCT_ADMITTINGDIAGNOSISCODE1,
	PCT_FACILITYTYPECODE1,
	PCT_ADMISSIONTYPECODE1,
	PCT_ADMISSIONSOURCECODE1,
	PCT_SVCLINECHARGEAMT1,
	PCT_SVCLINEREVENUECODE1,
	PCT_OCCURRENCECODE1,
	PCT_OCCURRENCESPANCODE1,
	PCT_VALUECODE1,
	PCT_CONDITIONCODE1,
	PCT_PATIENTSTATUSCODE1,
	PCT_PRINCIPALDIAGNOSISCODE1,
	PCT_ICD10DIAGNOSIS_CODE1,
	PCT_MULTIPLEPROCEDURECODE1,
	PCT_CDT_CODE1,
	PCT_CPT_CODE1,
	PCT_HIPPS_CODE1,
	PCT_SVCLINEPROCMOD1,
	PCT_SVCLINEADJREVENUECODE1,
	PCT_PROCEDURECODE1,
	PCT_SVCLINEADJUDICATIONPROCMOD1,
	PCT_BILLINGPROVNPI1,
	PCT_BILL_PROVIDERINTERNALID1,
	PCT_BILL_PROVIDERPIDSL1,
	PCT_AT_ATTENDINGPROVNPI1,
	PCT_AT_PROVIDERINTERNALID1,
	PCT_AT_PROVIDERPIDSL1,
	PCT_REF_REFERRINGPROVNPI1,
	PCT_REF_PROVIDERINTERNALID1,
	PCT_REF_PROVIDERPIDSL1,
	PCT_REN_RENDERINGPROVNPI1,
	PCT_REN_PROVIDERINTERNALID1,
	PCT_REN_PROVIDERPIDSL1,
	PCT_OOP_OTHEROPERPROVNPI1,
	PCT_OOP_PROVIDERINTERNALID1,
	PCT_OOP_PROVIDERPIDSL1,
	PCT_OP_OPERATINGPROVNPI1,
	PCT_OP_PROVIDERINTERNALID1,
	PCT_OP_PROVIDERPIDSL1,
	SUM_CLAIMFREQUENCYCODE1,
	SUM_STATEMENTDTP1,
	SUM_ADMISSIONDTP1,
	SUM_ADMITTINGDIAGNOSISCODE1,
	SUM_FACILITYTYPECODE1,
	SUM_ADMISSIONTYPECODE1,
	SUM_ADMISSIONSOURCECODE1,
	SUM_SVCLINECHARGEAMT1,
	SUM_SVCLINEREVENUECODE1,
	SUM_OCCURRENCECODE1,
	SUM_OCCURRENCESPANCODE1,
	SUM_VALUECODE1,
	SUM_CONDITIONCODE1,
	SUM_PATIENTSTATUSCODE1,
	SUM_PRINCIPALDIAGNOSISCODE1,
	SUM_ICD10DIAGNOSIS_CODE1,
	SUM_MULTIPLEPROCEDURECODE1,
	SUM_CDT_CODE1,
	SUM_CPT_CODE1,
	SUM_HIPPS_CODE1,
	SUM_SVCLINEPROCMOD1,
	SUM_SVCLINEADJREVENUECODE1,
	SUM_PROCEDURECODE1,
	SUM_SVCLINEADJUDICATIONPROCMOD1,
	SUM_BILLINGPROVNPI1,
	SUM_BILL_PROVIDERINTERNALID1,
	SUM_BILL_PROVIDERPIDSL1,
	SUM_AT_ATTENDINGPROVNPI1,
	SUM_AT_PROVIDERINTERNALID1,
	SUM_AT_PROVIDERPIDSL1,
	SUM_REF_REFERRINGPROVNPI1,
	SUM_REF_PROVIDERINTERNALID1,
	SUM_REF_PROVIDERPIDSL1,
	SUM_REN_RENDERINGPROVNPI1,
	SUM_REN_PROVIDERINTERNALID1,
	SUM_REN_PROVIDERPIDSL1,
	SUM_OOP_OTHEROPERPROVNPI1,
	SUM_OOP_PROVIDERINTERNALID1,
	SUM_OOP_PROVIDERPIDSL1,
	SUM_OP_OPERATINGPROVNPI11,
	SUM_OP_PROVIDERINTERNALID1,
	SUM_OP_PROVIDERPIDSL1,
	SUM_TOT_REX
) as
SELECT DISTINCT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
FILENAME,
RECORD_TYPE,
SUM_CLAIMFREQUENCYCODE1/SUM_TOT_REX PCT_CLAIMFREQUENCYCODE1,
SUM_STATEMENTDTP1/SUM_TOT_REX PCT_STATEMENTDTP1,
SUM_ADMISSIONDTP1/SUM_TOT_REX PCT_ADMISSIONDTP1,
SUM_ADMITTINGDIAGNOSISCODE1/SUM_TOT_REX PCT_ADMITTINGDIAGNOSISCODE1,
SUM_FACILITYTYPECODE1/SUM_TOT_REX PCT_FACILITYTYPECODE1,
SUM_ADMISSIONTYPECODE1/SUM_TOT_REX PCT_ADMISSIONTYPECODE1,
SUM_ADMISSIONSOURCECODE1/SUM_TOT_REX PCT_ADMISSIONSOURCECODE1,
SUM_SVCLINECHARGEAMT1/SUM_TOT_REX PCT_SVCLINECHARGEAMT1,
SUM_SVCLINEREVENUECODE1/SUM_TOT_REX PCT_SVCLINEREVENUECODE1,

SUM_OCCURRENCECODE1/SUM_TOT_REX PCT_OCCURRENCECODE1,
SUM_OCCURRENCESPANCODE1/SUM_TOT_REX PCT_OCCURRENCESPANCODE1,
SUM_VALUECODE1/SUM_TOT_REX PCT_VALUECODE1,
SUM_CONDITIONCODE1/SUM_TOT_REX PCT_CONDITIONCODE1,

SUM_PATIENTSTATUSCODE1/SUM_TOT_REX PCT_PATIENTSTATUSCODE1,
SUM_PRINCIPALDIAGNOSISCODE1/SUM_TOT_REX PCT_PRINCIPALDIAGNOSISCODE1,

SUM_ICD10DIAGNOSIS_CODE1/SUM_TOT_REX PCT_ICD10DIAGNOSIS_CODE1,

SUM_MULTIPLEPROCEDURECODE1/SUM_TOT_REX PCT_MULTIPLEPROCEDURECODE1,

SUM_CDT_CODE1/SUM_TOT_REX PCT_CDT_CODE1,
SUM_CPT_CODE1/SUM_TOT_REX PCT_CPT_CODE1,
SUM_HIPPS_CODE1/SUM_TOT_REX PCT_HIPPS_CODE1,

SUM_SVCLINEPROCMOD1/SUM_TOT_REX PCT_SVCLINEPROCMOD1,
SUM_SVCLINEADJREVENUECODE1/SUM_TOT_REX PCT_SVCLINEADJREVENUECODE1,
SUM_PROCEDURECODE1/SUM_TOT_REX PCT_PROCEDURECODE1,
SUM_SVCLINEADJUDICATIONPROCMOD1/SUM_TOT_REX PCT_SVCLINEADJUDICATIONPROCMOD1,

SUM_BILLINGPROVNPI1/SUM_TOT_REX PCT_BILLINGPROVNPI1,
SUM_BILL_PROVIDERINTERNALID1/SUM_TOT_REX PCT_BILL_PROVIDERINTERNALID1,
SUM_BILL_PROVIDERPIDSL1/SUM_TOT_REX PCT_BILL_PROVIDERPIDSL1,

SUM_AT_ATTENDINGPROVNPI1/SUM_TOT_REX PCT_AT_ATTENDINGPROVNPI1,
SUM_AT_PROVIDERINTERNALID1/SUM_TOT_REX PCT_AT_PROVIDERINTERNALID1,
SUM_AT_PROVIDERPIDSL1/SUM_TOT_REX PCT_AT_PROVIDERPIDSL1,

SUM_REF_REFERRINGPROVNPI1/SUM_TOT_REX PCT_REF_REFERRINGPROVNPI1,
SUM_REF_PROVIDERINTERNALID1/SUM_TOT_REX PCT_REF_PROVIDERINTERNALID1,
SUM_REF_PROVIDERPIDSL1/SUM_TOT_REX PCT_REF_PROVIDERPIDSL1,

SUM_REN_RENDERINGPROVNPI1/SUM_TOT_REX PCT_REN_RENDERINGPROVNPI1,
SUM_REN_PROVIDERINTERNALID1/SUM_TOT_REX PCT_REN_PROVIDERINTERNALID1,
SUM_REN_PROVIDERPIDSL1/SUM_TOT_REX PCT_REN_PROVIDERPIDSL1,

SUM_OOP_OTHEROPERPROVNPI1/SUM_TOT_REX PCT_OOP_OTHEROPERPROVNPI1,
SUM_OOP_PROVIDERINTERNALID1/SUM_TOT_REX PCT_OOP_PROVIDERINTERNALID1,
SUM_OOP_PROVIDERPIDSL1/SUM_TOT_REX PCT_OOP_PROVIDERPIDSL1,

SUM_OP_OPERATINGPROVNPI11/SUM_TOT_REX PCT_OP_OPERATINGPROVNPI1,
SUM_OP_PROVIDERINTERNALID1/SUM_TOT_REX PCT_OP_PROVIDERINTERNALID1,
SUM_OP_PROVIDERPIDSL1/SUM_TOT_REX PCT_OP_PROVIDERPIDSL1,

SUM_CLAIMFREQUENCYCODE1,
SUM_STATEMENTDTP1,
SUM_ADMISSIONDTP1,
SUM_ADMITTINGDIAGNOSISCODE1,
SUM_FACILITYTYPECODE1,
SUM_ADMISSIONTYPECODE1,
SUM_ADMISSIONSOURCECODE1,
SUM_SVCLINECHARGEAMT1,
SUM_SVCLINEREVENUECODE1,
SUM_OCCURRENCECODE1,
SUM_OCCURRENCESPANCODE1,
SUM_VALUECODE1,
SUM_CONDITIONCODE1,
SUM_PATIENTSTATUSCODE1,
SUM_PRINCIPALDIAGNOSISCODE1,
SUM_ICD10DIAGNOSIS_CODE1,
SUM_MULTIPLEPROCEDURECODE1,
SUM_CDT_CODE1,
SUM_CPT_CODE1,
SUM_HIPPS_CODE1,
SUM_SVCLINEPROCMOD1,
SUM_SVCLINEADJREVENUECODE1,
SUM_PROCEDURECODE1,
SUM_SVCLINEADJUDICATIONPROCMOD1,

SUM_BILLINGPROVNPI1,
SUM_BILL_PROVIDERINTERNALID1,
SUM_BILL_PROVIDERPIDSL1,

SUM_AT_ATTENDINGPROVNPI1,
SUM_AT_PROVIDERINTERNALID1,
SUM_AT_PROVIDERPIDSL1,

SUM_REF_REFERRINGPROVNPI1,
SUM_REF_PROVIDERINTERNALID1,
SUM_REF_PROVIDERPIDSL1,

SUM_REN_RENDERINGPROVNPI1,
SUM_REN_PROVIDERINTERNALID1,
SUM_REN_PROVIDERPIDSL1,

SUM_OOP_OTHEROPERPROVNPI1,
SUM_OOP_PROVIDERINTERNALID1,
SUM_OOP_PROVIDERPIDSL1,

SUM_OP_OPERATINGPROVNPI11,
SUM_OP_PROVIDERINTERNALID1,
SUM_OP_PROVIDERPIDSL1,

SUM_TOT_REX
FROM (
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
A.FILENAME,
RECORD_TYPE,
SUBMITTERID,
CASE WHEN A.CLAIM_TYPE = 'M' THEN PS."SubmitterLastOrgName"
     WHEN A.CLAIM_TYPE = 'D' THEN DS."SubmitterLastOrgName"
     ELSE S."SubmitterLastOrgName"
END AS SUBMITTERNAME,
CLAIM_TYPE,
SUM(CLAIMFREQUENCYCODE1) SUM_CLAIMFREQUENCYCODE1,
SUM(STATEMENTDTP1) SUM_STATEMENTDTP1,
SUM(ADMISSIONDTP1) SUM_ADMISSIONDTP1,
SUM(ADMITTINGDIAGNOSISCODE1) SUM_ADMITTINGDIAGNOSISCODE1,
SUM(FACILITYTYPECODE1) SUM_FACILITYTYPECODE1,
SUM(ADMISSIONTYPECODE1) SUM_ADMISSIONTYPECODE1,
SUM(ADMISSIONSOURCECODE1) SUM_ADMISSIONSOURCECODE1,
SUM(SVCLINECHARGEAMT1) SUM_SVCLINECHARGEAMT1,
SUM(SVCLINEREVENUECODE1) SUM_SVCLINEREVENUECODE1,

SUM(OCCURRENCECODE1) SUM_OCCURRENCECODE1,
SUM(OCCURRENCESPANCODE1) SUM_OCCURRENCESPANCODE1,

SUM(VALUECODE1) SUM_VALUECODE1,
SUM(CONDITIONCODE1) SUM_CONDITIONCODE1,

SUM(PATIENTSTATUSCODE1) SUM_PATIENTSTATUSCODE1,
SUM(PRINCIPALDIAGNOSISCODE1) SUM_PRINCIPALDIAGNOSISCODE1,

SUM(ICD10DIAGNOSIS_CODE1) SUM_ICD10DIAGNOSIS_CODE1,

SUM(MULTIPLEPROCEDURECODE1) SUM_MULTIPLEPROCEDURECODE1,

SUM(CDT_CODE1) SUM_CDT_CODE1,
SUM(CPT_CODE1) SUM_CPT_CODE1,
SUM(HIPPS_CODE1) SUM_HIPPS_CODE1,

SUM(SVCLINEPROCMOD1) SUM_SVCLINEPROCMOD1,
SUM(SVCLINEADJREVENUECODE1) SUM_SVCLINEADJREVENUECODE1,
SUM(PROCEDURECODE1) SUM_PROCEDURECODE1,
SUM(SVCLINEADJUDICATIONPROCMOD1) SUM_SVCLINEADJUDICATIONPROCMOD1,


SUM(BILLINGPROVNPI1) SUM_BILLINGPROVNPI1,
SUM(BILL_PROVIDERINTERNALID1) SUM_BILL_PROVIDERINTERNALID1,
SUM(BILL_PROVIDERPIDSL1) SUM_BILL_PROVIDERPIDSL1,

SUM(AT_ATTENDINGPROVNPI1) SUM_AT_ATTENDINGPROVNPI1,
SUM(AT_PROVIDERINTERNALID1) SUM_AT_PROVIDERINTERNALID1,
SUM(AT_PROVIDERPIDSL1) SUM_AT_PROVIDERPIDSL1,

SUM(REF_REFERRINGPROVNPI1) SUM_REF_REFERRINGPROVNPI1,
SUM(REF_PROVIDERINTERNALID1) SUM_REF_PROVIDERINTERNALID1,
SUM(REF_PROVIDERPIDSL1) SUM_REF_PROVIDERPIDSL1,

SUM(REN_RENDERINGPROVNPI1) SUM_REN_RENDERINGPROVNPI1,
SUM(REN_PROVIDERINTERNALID1) SUM_REN_PROVIDERINTERNALID1,
SUM(REN_PROVIDERPIDSL1) SUM_REN_PROVIDERPIDSL1,

SUM(OOP_OTHEROPERPROVNPI1) SUM_OOP_OTHEROPERPROVNPI1,
SUM(OOP_PROVIDERINTERNALID1) SUM_OOP_PROVIDERINTERNALID1,
SUM(OOP_PROVIDERPIDSL1) SUM_OOP_PROVIDERPIDSL1,

SUM(OP_OPERATINGPROVNPI1) SUM_OP_OPERATINGPROVNPI11,
SUM(OP_PROVIDERINTERNALID1) SUM_OP_PROVIDERINTERNALID1,
SUM(OP_PROVIDERPIDSL1) SUM_OP_PROVIDERPIDSL1,

SUM(TOT_REX) SUM_TOT_REX
FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_7_QA A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837I_FILE_STATISTICS S
    ON A.FILENAME = S."FileName" AND A.CLAIM_TYPE IN ('I','L','O')
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837P_FILE_STATISTICS PS
    ON A.FILENAME = PS."FileName" AND A.CLAIM_TYPE = 'M'
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837D_FILE_STATISTICS DS
    ON A.FILENAME = DS."FileName" AND A.CLAIM_TYPE = 'D'    
GROUP BY
RUN_DATE,
TRANSSETCONTROLNUM,
A.FILENAME,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
RECORD_TYPE
)
ORDER BY
RUN_DATE,
TRANSSETCONTROLNUM,
FILENAME,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
RECORD_TYPE
;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_7_QA_UNPIV(
	RUN_DATE,
	FILENAME,
	CLAIM_TYPE,
	RECORD_TYPE,
	MEASURE,
	TYPE,
	REC_CNT,
	SUBMITTERNAME,
	BENCHMARK_THRESHOLD
) as

SELECT DISTINCT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, REC_CNT,
S."SubmitterLastOrgName" AS SUBMITTERNAME,
L.BENCHMARK_THRESHOLD
FROM
(
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, COUNT(TYPE) AS REC_CNT
FROM (
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    RECORD_TYPE,
    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	STATEMENTDTP1X AS Statement_Date,
	ADMISSIONDTP1X AS Admission_Date,
	ADMITTINGDIAGNOSISCODE1X AS Admitting_Diagnosis_Code,
	FACILITYTYPECODE1X AS Facility_Type_Code,
	ADMISSIONTYPECODE1X AS Admission_Type_Code,
	ADMISSIONSOURCECODE1X AS Admission_Source_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEREVENUECODE1X AS Service_Line_Revenue_Code,
	OCCURRENCECODE1X AS Occurence_Code,
	OCCURRENCESPANCODE1X AS Occurrence_Span_Code,
	VALUECODE1X AS Value_Code,
	CONDITIONCODE1X AS Condition_Code,
	PATIENTSTATUSCODE1X AS Patient_Status_Code,
	PRINCIPALDIAGNOSISCODE1X AS Principal_Diag_Code,
	ICD10DIAGNOSIS_CODE1X AS ICD10_Diag_Code,
	MULTIPLEPROCEDURECODE1X AS Service_Line_Proc_Code,
	CDT_CODE1X AS CDT_Code,
	CPT_CODE1X AS CPT_Code,
	HIPPS_CODE1X AS HIPPS_Code,
	SVCLINEPROCMOD1X AS Service_Line_Proc_Mod,
	SVCLINEADJREVENUECODE1X AS Service_Line_Adjust_Revenue_Code,
	PROCEDURECODE1X AS Procedure_Code,
	SVCLINEADJUDICATIONPROCMOD1X AS Service_Line_Adj_Proc_Mod,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    AT_ATTENDINGPROVNPI1X Attending_Provider_NPI,
    AT_PROVIDERINTERNALID1X Attending_Provider_Internal_ID,
    AT_PROVIDERPIDSL1X Attending_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    OOP_OTHEROPERPROVNPI1X Other_Provider_NPI,
    OOP_PROVIDERINTERNALID1X Other_Provider_Internal_ID,
    OOP_PROVIDERPIDSL1X Other_Provider_PIDSL,

    OP_OPERATINGPROVNPI1X Operating_Provider_NPI,
    OP_PROVIDERINTERNALID1X Operating_Provider_Internal_ID,
    OP_PROVIDERPIDSL1X Operating_Provider_PIDSL
    
    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Statement_Date,
	Admission_Date,
	Admitting_Diagnosis_Code,
	Facility_Type_Code,
	Admission_Type_Code,
	Admission_Source_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
	Occurence_Code,
	Occurrence_Span_Code,
	Value_Code,
	Condition_Code,
	Patient_Status_Code,
	Principal_Diag_Code,
	ICD10_Diag_Code,
	Service_Line_Proc_Code,
	CDT_Code,
	CPT_Code,
	HIPPS_Code,
	Service_Line_Proc_Mod,
	Service_Line_Adjust_Revenue_Code,
	Procedure_Code,
	Service_Line_Adj_Proc_Mod,
    
	Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Attending_Provider_NPI,
    Attending_Provider_Internal_ID,
    Attending_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Other_Provider_NPI,
    Other_Provider_Internal_ID,
    Other_Provider_PIDSL,

    Operating_Provider_NPI,
    Operating_Provider_Internal_ID,
    Operating_Provider_PIDSL
)
) AS INF_B_SENDPRO_CLAIMS_DQ_7_UNPIV
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
)
GROUP BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837I_FILE_STATISTICS S
    ON A.FILENAME = S."FileName" AND A.CLAIM_TYPE IN ('I','L','O')
JOIN INF_B_SENDPRO_LOOKUP L ON A.MEASURE = L.BENCHMARK

ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_7_837I_UNPIV_DETAIL(
	RUN_DATE,
	FILENAME,
	CLAIM_TYPE,
	RECORD_TYPE,
	MEASURE,
	TYPE,
	PATIENTCONTROLNUM,
	NUMDTL,
	RNK,
	SUBMITTERNAME
) as

SELECT DISTINCT A.*,
S."SubmitterLastOrgName" AS SUBMITTERNAME
FROM
(

-- limit rank to 10 lines
SELECT *
FROM (
-- rank
  SELECT *,
                                            RANK ()
                                            OVER (PARTITION BY RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE
                                                  ORDER BY
                                                               RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE,
                                                               TYPE,
                                                               PATIENTCONTROLNUM,
                                                               NUMDTL)    AS rnk

  FROM (

-- only first claim line

SELECT *
  FROM (

-- core unpiv

SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, PatientControlNum, NumDtl  
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE, 
    RECORD_TYPE,
    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	STATEMENTDTP1X AS Statement_Date,
	ADMISSIONDTP1X AS Admission_Date,
	ADMITTINGDIAGNOSISCODE1X AS Admitting_Diagnosis_Code,
	FACILITYTYPECODE1X AS Facility_Type_Code,
	ADMISSIONTYPECODE1X AS Admission_Type_Code,
	ADMISSIONSOURCECODE1X AS Admission_Source_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEREVENUECODE1X AS Service_Line_Revenue_Code,
	OCCURRENCECODE1X AS Occurence_Code,
	OCCURRENCESPANCODE1X AS Occurrence_Span_Code,
	VALUECODE1X AS Value_Code,
	CONDITIONCODE1X AS Condition_Code,
	PATIENTSTATUSCODE1X AS Patient_Status_Code,
	PRINCIPALDIAGNOSISCODE1X AS Principal_Diag_Code,
	ICD10DIAGNOSIS_CODE1X AS ICD10_Diag_Code,
	MULTIPLEPROCEDURECODE1X AS Service_Line_Proc_Code,
	CDT_CODE1X AS CDT_Code,
	CPT_CODE1X AS CPT_Code,
	HIPPS_CODE1X AS HIPPS_Code,
	SVCLINEPROCMOD1X AS Service_Line_Proc_Mod,
	SVCLINEADJREVENUECODE1X AS Service_Line_Adjust_Revenue_Code,
	PROCEDURECODE1X AS Procedure_Code,
	SVCLINEADJUDICATIONPROCMOD1X AS Service_Line_Adj_Revenue_Code,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    AT_ATTENDINGPROVNPI1X Attending_Provider_NPI,
    AT_PROVIDERINTERNALID1X Attending_Provider_Internal_ID,
    AT_PROVIDERPIDSL1X Attending_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    OOP_OTHEROPERPROVNPI1X Other_Provider_NPI,
    OOP_PROVIDERINTERNALID1X Other_Provider_Internal_ID,
    OOP_PROVIDERPIDSL1X Other_Provider_PIDSL,

    OP_OPERATINGPROVNPI1X Operating_Provider_NPI,
    OP_PROVIDERINTERNALID1X Operating_Provider_Internal_ID,
    OP_PROVIDERPIDSL1X Operating_Provider_PIDSL,
    
    PatientControlNum, 
    NumDtl
    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Statement_Date,
	Admission_Date,
	Admitting_Diagnosis_Code,
	Facility_Type_Code,
	Admission_Type_Code,
	Admission_Source_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
	Occurence_Code,
	Occurrence_Span_Code,
	Value_Code,
	Condition_Code,
	Patient_Status_Code,
	Principal_Diag_Code,
	ICD10_Diag_Code,
	Service_Line_Proc_Code,
	CDT_Code,
	CPT_Code,
	HIPPS_Code,
	Service_Line_Proc_Mod,
	Service_Line_Adjust_Revenue_Code,
	Procedure_Code,
	Service_Line_Adj_Revenue_Code,

	Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Attending_Provider_NPI,
    Attending_Provider_Internal_ID,
    Attending_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Other_Provider_NPI,
    Other_Provider_Internal_ID,
    Other_Provider_PIDSL,

    Operating_Provider_NPI,
    Operating_Provider_Internal_ID,
    Operating_Provider_PIDSL

)
) AS UNPIV7
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE

)
-- only first claim line
    WHERE NUMDTL = 1
    )
-- add rank
)
-- limit rank to 10 line
WHERE rnk <= 10
) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837I_FILE_STATISTICS S
    ON A.FILENAME = S."FileName" AND A.CLAIM_TYPE IN ('I','L','O')
ORDER BY 
                                                               RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE,
                                                               TYPE,
                                                               PATIENTCONTROLNUM,
                                                               RNK
;

-------------  Dental

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7D_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	FILENAME,
	PATIENTCONTROLNUM,
	NUMDTL,
	CLAIM_TYPE,
	RECORD_TYPE,
	CLAIMFREQUENCYCODE1X,
	SVCLINECHARGEAMT1X,
	SVCLINEADJREVENUECODE1X,
	BILLINGPROVNPI1X,
	BILL_PROVIDERINTERNALID1X,
	BILL_PROVIDERPIDSL1X,
	REF_REFERRINGPROVNPI1X,
	REF_PROVIDERINTERNALID1X,
	REF_PROVIDERPIDSL1X,
	REN_RENDERINGPROVNPI1X,
	REN_PROVIDERINTERNALID1X,
	REN_PROVIDERPIDSL1X,
	SUP_SUPERVISINGPROVNPI1X,
	SUP_PROVIDERINTERNALID1X,
	SUP_PROVIDERPIDSL1X,
	ASST_ASSISTANTSURGEONPROVNPI1X,
	ASST_PROVIDERINTERNALID1X,
	ASST_PROVIDERPIDSL1X,
	TOT_REX
) as
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
FILENAME,
PATIENTCONTROLNUM,
NUMDTL,
CLAIM_TYPE,
RECORD_TYPE,
CLAIMFREQUENCYCODE1X,
SVCLINECHARGEAMT1X,
SVCLINEADJREVENUECODE1X,

BILLINGPROVNPI1X,
BILL_PROVIDERINTERNALID1X,
BILL_PROVIDERPIDSL1X,

REF_REFERRINGPROVNPI1X,
REF_PROVIDERINTERNALID1X,
REF_PROVIDERPIDSL1X,

REN_RENDERINGPROVNPI1X,
REN_PROVIDERINTERNALID1X,
REN_PROVIDERPIDSL1X,

SUP_SUPERVISINGPROVNPI1X,
SUP_PROVIDERINTERNALID1X,
SUP_PROVIDERPIDSL1X,

ASST_ASSISTANTSURGEONPROVNPI1X,
ASST_PROVIDERINTERNALID1X,
ASST_PROVIDERPIDSL1X,

TOT_REX
FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7D_QA;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_7D_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	FILENAME,
	PATIENTCONTROLNUM,
	NUMDTL,
	CLAIM_TYPE,
	RECORD_TYPE,
	CLAIMFREQUENCYCODE1,
	SVCLINECHARGEAMT1,
	SVCLINEADJREVENUECODE1,
	BILLINGPROVNPI1,
	BILL_PROVIDERINTERNALID1,
	BILL_PROVIDERPIDSL1,
	REF_REFERRINGPROVNPI1,
	REF_PROVIDERINTERNALID1,
	REF_PROVIDERPIDSL1,
	REN_RENDERINGPROVNPI1,
	REN_PROVIDERINTERNALID1,
	REN_PROVIDERPIDSL1,
	SUP_SUPERVISINGPROVNPI1,
	SUP_PROVIDERINTERNALID1,
	SUP_PROVIDERPIDSL1,
	ASST_ASSISTANTSURGEONPROVNPI1,
	ASST_PROVIDERINTERNALID1,
	ASST_PROVIDERPIDSL1,
	TOT_REX
) as
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
FILENAME,
PATIENTCONTROLNUM,

NUMDTL,
CLAIM_TYPE,
RECORD_TYPE,
CLAIMFREQUENCYCODE1,
SVCLINECHARGEAMT1,
SVCLINEADJREVENUECODE1,

BILLINGPROVNPI1,
BILL_PROVIDERINTERNALID1,
BILL_PROVIDERPIDSL1,

REF_REFERRINGPROVNPI1,
REF_PROVIDERINTERNALID1,
REF_PROVIDERPIDSL1,

REN_RENDERINGPROVNPI1,
REN_PROVIDERINTERNALID1,
REN_PROVIDERPIDSL1,

SUP_SUPERVISINGPROVNPI1,
SUP_PROVIDERINTERNALID1,
SUP_PROVIDERPIDSL1,

ASST_ASSISTANTSURGEONPROVNPI1,
ASST_PROVIDERINTERNALID1,
ASST_PROVIDERPIDSL1,

TOT_REX
FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7D_QA;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_STATS_7D_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	SUBMITTERNAME,
	CLAIM_TYPE,
	FILENAME,
	RECORD_TYPE,
	PCT_CLAIMFREQUENCYCODE1,
	PCT_SVCLINECHARGEAMT1,
	PCT_BILLINGPROVNPI1,
	PCT_BILL_PROVIDERINTERNALID1,
	PCT_BILL_PROVIDERPIDSL1,
	PCT_REF_REFERRINGPROVNPI1,
	PCT_REF_PROVIDERINTERNALID1,
	PCT_REF_PROVIDERPIDSL1,
	PCT_REN_RENDERINGPROVNPI1,
	PCT_REN_PROVIDERINTERNALID1,
	PCT_REN_PROVIDERPIDSL1,
	PCT_SUP_SUPERVISINGPROVNPI1,
	PCT_SUP_PROVIDERINTERNALID1,
	PCT_SUP_PROVIDERPIDSL1,
	PCT_ASST_ASSISTANTSURGEONPROVNPI1,
	PCT_ASST_PROVIDERINTERNALID1,
	PCT_ASST_PROVIDERPIDSL1,
	SUM_CLAIMFREQUENCYCODE1,
	SUM_SVCLINECHARGEAMT1,
	SUM_BILLINGPROVNPI1,
	SUM_BILL_PROVIDERINTERNALID1,
	SUM_BILL_PROVIDERPIDSL1,
	SUM_REF_REFERRINGPROVNPI1,
	SUM_REF_PROVIDERINTERNALID1,
	SUM_REF_PROVIDERPIDSL1,
	SUM_REN_RENDERINGPROVNPI1,
	SUM_REN_PROVIDERINTERNALID1,
	SUM_REN_PROVIDERPIDSL1,
	SUM_SUP_SUPERVISINGPROVNPI1,
	SUM_SUP_PROVIDERINTERNALID1,
	SUM_SUP_PROVIDERPIDSL1,
	SUM_ASST_ASSISTANTSURGEONPROVNPI1,
	SUM_ASST_PROVIDERINTERNALID1,
	SUM_ASST_PROVIDERPIDSL1,
	SUM_TOT_REX
) as
SELECT DISTINCT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
FILENAME,
RECORD_TYPE,

SUM_CLAIMFREQUENCYCODE1/SUM_TOT_REX PCT_CLAIMFREQUENCYCODE1,
SUM_SVCLINECHARGEAMT1/SUM_TOT_REX PCT_SVCLINECHARGEAMT1,

SUM_BILLINGPROVNPI1/SUM_TOT_REX PCT_BILLINGPROVNPI1,
SUM_BILL_PROVIDERINTERNALID1/SUM_TOT_REX PCT_BILL_PROVIDERINTERNALID1,
SUM_BILL_PROVIDERPIDSL1/SUM_TOT_REX PCT_BILL_PROVIDERPIDSL1,

SUM_REF_REFERRINGPROVNPI1/SUM_TOT_REX PCT_REF_REFERRINGPROVNPI1,
SUM_REF_PROVIDERINTERNALID1/SUM_TOT_REX PCT_REF_PROVIDERINTERNALID1,
SUM_REF_PROVIDERPIDSL1/SUM_TOT_REX PCT_REF_PROVIDERPIDSL1,

SUM_REN_RENDERINGPROVNPI1/SUM_TOT_REX PCT_REN_RENDERINGPROVNPI1,
SUM_REN_PROVIDERINTERNALID1/SUM_TOT_REX PCT_REN_PROVIDERINTERNALID1,
SUM_REN_PROVIDERPIDSL1/SUM_TOT_REX PCT_REN_PROVIDERPIDSL1,

SUM_SUP_SUPERVISINGPROVNPI1/SUM_TOT_REX PCT_SUP_SUPERVISINGPROVNPI1,
SUM_SUP_PROVIDERINTERNALID1/SUM_TOT_REX PCT_SUP_PROVIDERINTERNALID1,
SUM_SUP_PROVIDERPIDSL1/SUM_TOT_REX PCT_SUP_PROVIDERPIDSL1,

SUM_ASST_ASSISTANTSURGEONPROVNPI1/SUM_TOT_REX PCT_ASST_ASSISTANTSURGEONPROVNPI1,
SUM_ASST_PROVIDERINTERNALID1/SUM_TOT_REX PCT_ASST_PROVIDERINTERNALID1,
SUM_ASST_PROVIDERPIDSL1/SUM_TOT_REX PCT_ASST_PROVIDERPIDSL1,

SUM_CLAIMFREQUENCYCODE1,
SUM_SVCLINECHARGEAMT1,

SUM_BILLINGPROVNPI1,
SUM_BILL_PROVIDERINTERNALID1,
SUM_BILL_PROVIDERPIDSL1,

SUM_REF_REFERRINGPROVNPI1,
SUM_REF_PROVIDERINTERNALID1,
SUM_REF_PROVIDERPIDSL1,

SUM_REN_RENDERINGPROVNPI1,
SUM_REN_PROVIDERINTERNALID1,
SUM_REN_PROVIDERPIDSL1,

SUM_SUP_SUPERVISINGPROVNPI1,
SUM_SUP_PROVIDERINTERNALID1,
SUM_SUP_PROVIDERPIDSL1,

SUM_ASST_ASSISTANTSURGEONPROVNPI1,
SUM_ASST_PROVIDERINTERNALID1,
SUM_ASST_PROVIDERPIDSL1,

SUM_TOT_REX
FROM (
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
A.FILENAME,
SUBMITTERID,
CASE WHEN A.CLAIM_TYPE = 'M' THEN PS."SubmitterLastOrgName"
     WHEN A.CLAIM_TYPE = 'D' THEN DS."SubmitterLastOrgName"
     ELSE S."SubmitterLastOrgName"
END AS SUBMITTERNAME,
CLAIM_TYPE,
RECORD_TYPE,

SUM(CLAIMFREQUENCYCODE1) SUM_CLAIMFREQUENCYCODE1,
SUM(SVCLINECHARGEAMT1) SUM_SVCLINECHARGEAMT1,

SUM(BILLINGPROVNPI1) SUM_BILLINGPROVNPI1,
SUM(BILL_PROVIDERINTERNALID1) SUM_BILL_PROVIDERINTERNALID1,
SUM(BILL_PROVIDERPIDSL1) SUM_BILL_PROVIDERPIDSL1,

SUM(REF_REFERRINGPROVNPI1) SUM_REF_REFERRINGPROVNPI1,
SUM(REF_PROVIDERINTERNALID1) SUM_REF_PROVIDERINTERNALID1,
SUM(REF_PROVIDERPIDSL1) SUM_REF_PROVIDERPIDSL1,

SUM(REN_RENDERINGPROVNPI1) SUM_REN_RENDERINGPROVNPI1,
SUM(REN_PROVIDERINTERNALID1) SUM_REN_PROVIDERINTERNALID1,
SUM(REN_PROVIDERPIDSL1) SUM_REN_PROVIDERPIDSL1,

SUM(SUP_SUPERVISINGPROVNPI1) SUM_SUP_SUPERVISINGPROVNPI1,
SUM(SUP_PROVIDERINTERNALID1) SUM_SUP_PROVIDERINTERNALID1,
SUM(SUP_PROVIDERPIDSL1) SUM_SUP_PROVIDERPIDSL1,

SUM(ASST_ASSISTANTSURGEONPROVNPI1) SUM_ASST_ASSISTANTSURGEONPROVNPI1,
SUM(ASST_PROVIDERINTERNALID1) SUM_ASST_PROVIDERINTERNALID1,
SUM(ASST_PROVIDERPIDSL1) SUM_ASST_PROVIDERPIDSL1,

SUM(TOT_REX) SUM_TOT_REX
FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_7D_QA A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837I_FILE_STATISTICS S
    ON A.FILENAME = S."FileName" AND A.CLAIM_TYPE IN ('I','L','O')
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837P_FILE_STATISTICS PS
    ON A.FILENAME = PS."FileName" AND A.CLAIM_TYPE = 'M'
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837D_FILE_STATISTICS DS
    ON A.FILENAME = DS."FileName" AND A.CLAIM_TYPE = 'D'    
GROUP BY
RUN_DATE,
TRANSSETCONTROLNUM,
A.FILENAME,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
RECORD_TYPE
)
ORDER BY
RUN_DATE,
TRANSSETCONTROLNUM,
FILENAME,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
RECORD_TYPE
;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_7D_QA_UNPIV(
	RUN_DATE,
	FILENAME,
	CLAIM_TYPE,
	RECORD_TYPE,
	MEASURE,
	TYPE,
	REC_CNT,
	SUBMITTERNAME,
	BENCHMARK_THRESHOLD
) as

SELECT DISTINCT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, REC_CNT,
DS."SubmitterLastOrgName" AS SUBMITTERNAME,
L.BENCHMARK_THRESHOLD

FROM
(
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, COUNT(TYPE) AS REC_CNT
FROM (
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    RECORD_TYPE,
    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEADJREVENUECODE1X AS Service_Line_Revenue_Code,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    SUP_SUPERVISINGPROVNPI1X Supervising_Provider_NPI,
    SUP_PROVIDERINTERNALID1X Supervising_Provider_Internal_ID,
    SUP_PROVIDERPIDSL1X Supervising_Provider_PIDSL,

    ASST_ASSISTANTSURGEONPROVNPI1X Assistant_Surg_Provider_NPI,    
    ASST_PROVIDERINTERNALID1X Assistant_Surg_Provider_Internal_ID,
    ASST_PROVIDERPIDSL1X Assistant_Surg_Provider_PIDSL
    
    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7D_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
    
    Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Supervising_Provider_NPI,
    Supervising_Provider_Internal_ID,
    Supervising_Provider_PIDSL,

    Assistant_Surg_Provider_NPI,
    Assistant_Surg_Provider_Internal_ID,
    Assistant_Surg_Provider_PIDSL
)
) AS INF_B_SENDPRO_CLAIMS_DQ_7D_UNPIV
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
)
GROUP BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837D_FILE_STATISTICS DS
    ON A.FILENAME = DS."FileName" AND A.CLAIM_TYPE = 'D'
JOIN INF_B_SENDPRO_LOOKUP L ON A.MEASURE = L.BENCHMARK
ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_7_837D_UNPIV_DETAIL(
	RUN_DATE,
	FILENAME,
	CLAIM_TYPE,
	RECORD_TYPE,
	MEASURE,
	TYPE,
	PATIENTCONTROLNUM,
	NUMDTL,
	RNK,
	SUBMITTERNAME
) as

SELECT DISTINCT A.*,
DS."SubmitterLastOrgName" AS SUBMITTERNAME
FROM
(

-- limit rank to 10 lines
SELECT *
FROM (
-- rank
  SELECT *,
                                            RANK ()
                                            OVER (PARTITION BY RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE
                                                  ORDER BY
                                                               RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE,
                                                               TYPE,
                                                               PATIENTCONTROLNUM,
                                                               NUMDTL)    AS rnk

  FROM (

-- only first claim line

SELECT *
  FROM (

-- core unpiv

SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, PatientControlNum, NumDtl  
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    RECORD_TYPE,
    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEADJREVENUECODE1X AS Service_Line_Revenue_Code,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    SUP_SUPERVISINGPROVNPI1X Supervising_Provider_NPI,
    SUP_PROVIDERINTERNALID1X Supervising_Provider_Internal_ID,
    SUP_PROVIDERPIDSL1X Supervising_Provider_PIDSL,

    ASST_ASSISTANTSURGEONPROVNPI1X Assistant_Surg_Provider_NPI,    
    ASST_PROVIDERINTERNALID1X Assistant_Surg_Provider_Internal_ID,
    ASST_PROVIDERPIDSL1X Assistant_Surg_Provider_PIDSL,
    
    PatientControlNum, 
    NumDtl
    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7D_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
    
    Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Supervising_Provider_NPI,
    Supervising_Provider_Internal_ID,
    Supervising_Provider_PIDSL,

    Assistant_Surg_Provider_NPI,
    Assistant_Surg_Provider_Internal_ID,
    Assistant_Surg_Provider_PIDSL

)
) AS UNPIV7D
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE

)
-- only first claim line
    WHERE NUMDTL = 1
    )
-- add rank
)
-- limit rank to 10 line
WHERE rnk <= 10
) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837D_FILE_STATISTICS DS
    ON A.FILENAME = DS."FileName" AND A.CLAIM_TYPE = 'D'
ORDER BY 
                                                               RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE,
                                                               TYPE,
                                                               PATIENTCONTROLNUM,
                                                               RNK
;

----------- Professional

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7M_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	FILENAME,
	PATIENTCONTROLNUM,
	NUMDTL,
	CLAIM_TYPE,
	RECORD_TYPE,
	CLAIMFREQUENCYCODE1X,
	STATEMENTDTP1X,
	ADMISSIONDTP1X,
	BILLINGPROVNPI1X,
	ADMITTINGDIAGNOSISCODE1X,
	FACILITYTYPECODE1X,
	ADMISSIONTYPECODE1X,
	ADMISSIONSOURCECODE1X,
	SVCLINECHARGEAMT1X,
	SVCLINEREVENUECODE1X,
	OCCURRENCECODE1X,
	OCCURRENCESPANCODE1X,
	VALUECODE1X,
	CONDITIONCODE1X,
	PATIENTSTATUSCODE1X,
	PRINCIPALDIAGNOSISCODE1X,
	ICD10DIAGNOSIS_CODE1X,
	MULTIPLEPROCEDURECODE1X,
	CDT_CODE1X,
	CPT_CODE1X,
	HIPPS_CODE1X,
	SVCLINEPROCMOD1X,
	SVCLINEADJREVENUECODE1X,
	PROCEDURECODE1X,
	SVCLINEADJUDICATIONPROCMOD1X,
	BILL_PROVIDERINTERNALID1X,
	BILL_PROVIDERPIDSL1X,
	REF_REFERRINGPROVNPI1X,
	REF_PROVIDERINTERNALID1X,
	REF_PROVIDERPIDSL1X,
	REN_RENDERINGPROVNPI1X,
	REN_PROVIDERINTERNALID1X,
	REN_PROVIDERPIDSL1X,
	SUP_SUPERVISINGPROVNPI1X,
	SUP_PROVIDERINTERNALID1X,
	SUP_PROVIDERPIDSL1X,
	ORD_ORDERINGPROVID1X,
	ORD_PROVIDERINTERNALID1X,
	ORD_PROVIDERPIDSL1X,
	TOT_REX
) as
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
FILENAME,
PATIENTCONTROLNUM,
NUMDTL,
CLAIM_TYPE,
RECORD_TYPE,
CLAIMFREQUENCYCODE1X,
STATEMENTDTP1X,
ADMISSIONDTP1X,
BILLINGPROVNPI1X,
ADMITTINGDIAGNOSISCODE1X,
FACILITYTYPECODE1X,
ADMISSIONTYPECODE1X,
ADMISSIONSOURCECODE1X,
SVCLINECHARGEAMT1X,
SVCLINEREVENUECODE1X,
OCCURRENCECODE1X,
OCCURRENCESPANCODE1X,
VALUECODE1X,
CONDITIONCODE1X,
PATIENTSTATUSCODE1X,
PRINCIPALDIAGNOSISCODE1X,
ICD10DIAGNOSIS_CODE1X,
MULTIPLEPROCEDURECODE1X,
CDT_CODE1X,
CPT_CODE1X,
HIPPS_CODE1X,
SVCLINEPROCMOD1X,
SVCLINEADJREVENUECODE1X,
PROCEDURECODE1X,
SVCLINEADJUDICATIONPROCMOD1X,
BILL_PROVIDERINTERNALID1X,
BILL_PROVIDERPIDSL1X,

REF_REFERRINGPROVNPI1X,
REF_PROVIDERINTERNALID1X,
REF_PROVIDERPIDSL1X,

REN_RENDERINGPROVNPI1X,
REN_PROVIDERINTERNALID1X,
REN_PROVIDERPIDSL1X,

SUP_SUPERVISINGPROVNPI1X,
SUP_PROVIDERINTERNALID1X,
SUP_PROVIDERPIDSL1X,

ORD_ORDERINGPROVID1X,
ORD_PROVIDERINTERNALID1X,
ORD_PROVIDERPIDSL1X,

TOT_REX
FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7M_QA;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_7M_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	FILENAME,
	PATIENTCONTROLNUM,
	NUMDTL,
	CLAIM_TYPE,
	RECORD_TYPE,
	CLAIMFREQUENCYCODE1,
	STATEMENTDTP1,
	ADMISSIONDTP1,
	BILLINGPROVNPI1,
	ADMITTINGDIAGNOSISCODE1,
	FACILITYTYPECODE1,
	ADMISSIONTYPECODE1,
	ADMISSIONSOURCECODE1,
	SVCLINECHARGEAMT1,
	SVCLINEREVENUECODE1,
	OCCURRENCECODE1,
	OCCURRENCESPANCODE1,
	VALUECODE1,
	CONDITIONCODE1,
	PATIENTSTATUSCODE1,
	PRINCIPALDIAGNOSISCODE1,
	ICD10DIAGNOSIS_CODE1,
	MULTIPLEPROCEDURECODE1,
	CDT_CODE1,
	CPT_CODE1,
	HIPPS_CODE1,
	SVCLINEPROCMOD1,
	SVCLINEADJREVENUECODE1,
	PROCEDURECODE1,
	SVCLINEADJUDICATIONPROCMOD1,
	BILL_PROVIDERINTERNALID1,
	BILL_PROVIDERPIDSL1,
	REF_REFERRINGPROVNPI1,
	REF_PROVIDERINTERNALID1,
	REF_PROVIDERPIDSL1,
	REN_RENDERINGPROVNPI1,
	REN_PROVIDERINTERNALID1,
	REN_PROVIDERPIDSL1,
	SUP_SUPERVISINGPROVNPI1,
	SUP_PROVIDERINTERNALID1,
	SUP_PROVIDERPIDSL1,
	ORD_ORDERINGPROVID1,
	ORD_PROVIDERINTERNALID1,
	ORD_PROVIDERPIDSL1,
	TOT_REX
) as
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
FILENAME,
PATIENTCONTROLNUM,
NUMDTL,
CLAIM_TYPE,
RECORD_TYPE,
CLAIMFREQUENCYCODE1,
STATEMENTDTP1,
ADMISSIONDTP1,
BILLINGPROVNPI1,
ADMITTINGDIAGNOSISCODE1,
FACILITYTYPECODE1,
ADMISSIONTYPECODE1,
ADMISSIONSOURCECODE1,
SVCLINECHARGEAMT1,
SVCLINEREVENUECODE1,
OCCURRENCECODE1,
OCCURRENCESPANCODE1,
VALUECODE1,
CONDITIONCODE1,
PATIENTSTATUSCODE1,
PRINCIPALDIAGNOSISCODE1,
ICD10DIAGNOSIS_CODE1,
MULTIPLEPROCEDURECODE1,
CDT_CODE1,
CPT_CODE1,
HIPPS_CODE1,
SVCLINEPROCMOD1,
SVCLINEADJREVENUECODE1,
PROCEDURECODE1,
SVCLINEADJUDICATIONPROCMOD1,

BILL_PROVIDERINTERNALID1,
BILL_PROVIDERPIDSL1,

REF_REFERRINGPROVNPI1,
REF_PROVIDERINTERNALID1,
REF_PROVIDERPIDSL1,

REN_RENDERINGPROVNPI1,
REN_PROVIDERINTERNALID1,
REN_PROVIDERPIDSL1,

SUP_SUPERVISINGPROVNPI1,
SUP_PROVIDERINTERNALID1,
SUP_PROVIDERPIDSL1,

ORD_ORDERINGPROVID1,
ORD_PROVIDERINTERNALID1,
ORD_PROVIDERPIDSL1,

TOT_REX
FROM MHTEAM.DWDQ.INF_B_SENDPRO_CLAIMS_DQ_7M_QA;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_STATS_7M_QA(
	RUN_DATE,
	TRANSSETCONTROLNUM,
	SUBMITTERID,
	SUBMITTERNAME,
	CLAIM_TYPE,
	FILENAME,
	RECORD_TYPE,
	PCT_CLAIMFREQUENCYCODE1,
	PCT_STATEMENTDTP1,
	PCT_ADMISSIONDTP1,
	PCT_BILLINGPROVNPI1,
	PCT_ADMITTINGDIAGNOSISCODE1,
	PCT_FACILITYTYPECODE1,
	PCT_ADMISSIONTYPECODE1,
	PCT_ADMISSIONSOURCECODE1,
	PCT_SVCLINECHARGEAMT1,
	PCT_SVCLINEREVENUECODE1,
	PCT_OCCURRENCECODE1,
	PCT_OCCURRENCESPANCODE1,
	PCT_VALUECODE1,
	PCT_CONDITIONCODE1,
	PCT_PATIENTSTATUSCODE1,
	PCT_PRINCIPALDIAGNOSISCODE1,
	PCT_ICD10DIAGNOSIS_CODE1,
	PCT_MULTIPLEPROCEDURECODE1,
	PCT_CDT_CODE1,
	PCT_CPT_CODE1,
	PCT_HIPPS_CODE1,
	PCT_SVCLINEPROCMOD1,
	PCT_SVCLINEADJREVENUECODE1,
	PCT_PROCEDURECODE1,
	PCT_SVCLINEADJUDICATIONPROCMOD1,
	PCT_BILL_PROVIDERINTERNALID1,
	PCT_BILL_PROVIDERPIDSL1,
	PCT_REF_REFERRINGPROVNPI1,
	PCT_REF_PROVIDERINTERNALID1,
	PCT_REF_PROVIDERPIDSL1,
	PCT_REN_RENDERINGPROVNPI1,
	PCT_REN_PROVIDERINTERNALID1,
	PCT_REN_PROVIDERPIDSL1,
	PCT_SUP_SUPERVISINGPROVNPI1,
	PCT_SUP_PROVIDERINTERNALID1,
	PCT_SUP_PROVIDERPIDSL1,
	PCT_ORD_ORDERINGPROVID1,
	PCT_ORD_PROVIDERINTERNALID1,
	PCT_ORD_PROVIDERPIDSL1,
	SUM_CLAIMFREQUENCYCODE1,
	SUM_STATEMENTDTP1,
	SUM_ADMISSIONDTP1,
	SUM_BILLINGPROVNPI1,
	SUM_ADMITTINGDIAGNOSISCODE1,
	SUM_FACILITYTYPECODE1,
	SUM_ADMISSIONTYPECODE1,
	SUM_ADMISSIONSOURCECODE1,
	SUM_SVCLINECHARGEAMT1,
	SUM_SVCLINEREVENUECODE1,
	SUM_OCCURRENCECODE1,
	SUM_OCCURRENCESPANCODE1,
	SUM_VALUECODE1,
	SUM_CONDITIONCODE1,
	SUM_PATIENTSTATUSCODE1,
	SUM_PRINCIPALDIAGNOSISCODE1,
	SUM_ICD10DIAGNOSIS_CODE1,
	SUM_MULTIPLEPROCEDURECODE1,
	SUM_CDT_CODE1,
	SUM_CPT_CODE1,
	SUM_HIPPS_CODE1,
	SUM_SVCLINEPROCMOD1,
	SUM_SVCLINEADJREVENUECODE1,
	SUM_PROCEDURECODE1,
	SUM_SVCLINEADJUDICATIONPROCMOD1,
	SUM_BILL_PROVIDERINTERNALID1,
	SUM_BILL_PROVIDERPIDSL1,
	SUM_REF_REFERRINGPROVNPI1,
	SUM_REF_PROVIDERINTERNALID1,
	SUM_REF_PROVIDERPIDSL1,
	SUM_REN_RENDERINGPROVNPI1,
	SUM_REN_PROVIDERINTERNALID1,
	SUM_REN_PROVIDERPIDSL1,
	SUM_SUP_SUPERVISINGPROVNPI1,
	SUM_SUP_PROVIDERINTERNALID1,
	SUM_SUP_PROVIDERPIDSL1,
	SUM_ORD_ORDERINGPROVID1,
	SUM_ORD_PROVIDERINTERNALID1,
	SUM_ORD_PROVIDERPIDSL1,
	SUM_TOT_REX
) as
SELECT DISTINCT
RUN_DATE,
TRANSSETCONTROLNUM,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
FILENAME,
RECORD_TYPE,
SUM_CLAIMFREQUENCYCODE1/SUM_TOT_REX PCT_CLAIMFREQUENCYCODE1,
SUM_STATEMENTDTP1/SUM_TOT_REX PCT_STATEMENTDTP1,
SUM_ADMISSIONDTP1/SUM_TOT_REX PCT_ADMISSIONDTP1,
SUM_BILLINGPROVNPI1/SUM_TOT_REX PCT_BILLINGPROVNPI1,
SUM_ADMITTINGDIAGNOSISCODE1/SUM_TOT_REX PCT_ADMITTINGDIAGNOSISCODE1,
SUM_FACILITYTYPECODE1/SUM_TOT_REX PCT_FACILITYTYPECODE1,
SUM_ADMISSIONTYPECODE1/SUM_TOT_REX PCT_ADMISSIONTYPECODE1,
SUM_ADMISSIONSOURCECODE1/SUM_TOT_REX PCT_ADMISSIONSOURCECODE1,
SUM_SVCLINECHARGEAMT1/SUM_TOT_REX PCT_SVCLINECHARGEAMT1,
SUM_SVCLINEREVENUECODE1/SUM_TOT_REX PCT_SVCLINEREVENUECODE1,

SUM_OCCURRENCECODE1/SUM_TOT_REX PCT_OCCURRENCECODE1,
SUM_OCCURRENCESPANCODE1/SUM_TOT_REX PCT_OCCURRENCESPANCODE1,
SUM_VALUECODE1/SUM_TOT_REX PCT_VALUECODE1,
SUM_CONDITIONCODE1/SUM_TOT_REX PCT_CONDITIONCODE1,

SUM_PATIENTSTATUSCODE1/SUM_TOT_REX PCT_PATIENTSTATUSCODE1,
SUM_PRINCIPALDIAGNOSISCODE1/SUM_TOT_REX PCT_PRINCIPALDIAGNOSISCODE1,

SUM_ICD10DIAGNOSIS_CODE1/SUM_TOT_REX PCT_ICD10DIAGNOSIS_CODE1,

SUM_MULTIPLEPROCEDURECODE1/SUM_TOT_REX PCT_MULTIPLEPROCEDURECODE1,

SUM_CDT_CODE1/SUM_TOT_REX PCT_CDT_CODE1,
SUM_CPT_CODE1/SUM_TOT_REX PCT_CPT_CODE1,
SUM_HIPPS_CODE1/SUM_TOT_REX PCT_HIPPS_CODE1,

SUM_SVCLINEPROCMOD1/SUM_TOT_REX PCT_SVCLINEPROCMOD1,
SUM_SVCLINEADJREVENUECODE1/SUM_TOT_REX PCT_SVCLINEADJREVENUECODE1,
SUM_PROCEDURECODE1/SUM_TOT_REX PCT_PROCEDURECODE1,
SUM_SVCLINEADJUDICATIONPROCMOD1/SUM_TOT_REX PCT_SVCLINEADJUDICATIONPROCMOD1,

SUM_BILL_PROVIDERINTERNALID1/SUM_TOT_REX PCT_BILL_PROVIDERINTERNALID1,
SUM_BILL_PROVIDERPIDSL1/SUM_TOT_REX PCT_BILL_PROVIDERPIDSL1,

SUM_REF_REFERRINGPROVNPI1/SUM_TOT_REX PCT_REF_REFERRINGPROVNPI1,
SUM_REF_PROVIDERINTERNALID1/SUM_TOT_REX PCT_REF_PROVIDERINTERNALID1,
SUM_REF_PROVIDERPIDSL1/SUM_TOT_REX PCT_REF_PROVIDERPIDSL1,

SUM_REN_RENDERINGPROVNPI1/SUM_TOT_REX PCT_REN_RENDERINGPROVNPI1,
SUM_REN_PROVIDERINTERNALID1/SUM_TOT_REX PCT_REN_PROVIDERINTERNALID1,
SUM_REN_PROVIDERPIDSL1/SUM_TOT_REX PCT_REN_PROVIDERPIDSL1,

SUM_SUP_SUPERVISINGPROVNPI1/SUM_TOT_REX PCT_SUP_SUPERVISINGPROVNPI1,
SUM_SUP_PROVIDERINTERNALID1/SUM_TOT_REX PCT_SUP_PROVIDERINTERNALID1,
SUM_SUP_PROVIDERPIDSL1/SUM_TOT_REX PCT_SUP_PROVIDERPIDSL1,

SUM_ORD_ORDERINGPROVID1/SUM_TOT_REX PCT_ORD_ORDERINGPROVID1,
SUM_ORD_PROVIDERINTERNALID1/SUM_TOT_REX PCT_ORD_PROVIDERINTERNALID1,
SUM_ORD_PROVIDERPIDSL1/SUM_TOT_REX PCT_ORD_PROVIDERPIDSL1,

SUM_CLAIMFREQUENCYCODE1,
SUM_STATEMENTDTP1,
SUM_ADMISSIONDTP1,
SUM_BILLINGPROVNPI1,
SUM_ADMITTINGDIAGNOSISCODE1,
SUM_FACILITYTYPECODE1,
SUM_ADMISSIONTYPECODE1,
SUM_ADMISSIONSOURCECODE1,
SUM_SVCLINECHARGEAMT1,
SUM_SVCLINEREVENUECODE1,
SUM_OCCURRENCECODE1,
SUM_OCCURRENCESPANCODE1,
SUM_VALUECODE1,
SUM_CONDITIONCODE1,
SUM_PATIENTSTATUSCODE1,
SUM_PRINCIPALDIAGNOSISCODE1,
SUM_ICD10DIAGNOSIS_CODE1,
SUM_MULTIPLEPROCEDURECODE1,
SUM_CDT_CODE1,
SUM_CPT_CODE1,
SUM_HIPPS_CODE1,
SUM_SVCLINEPROCMOD1,
SUM_SVCLINEADJREVENUECODE1,
SUM_PROCEDURECODE1,
SUM_SVCLINEADJUDICATIONPROCMOD1,

SUM_BILL_PROVIDERINTERNALID1,
SUM_BILL_PROVIDERPIDSL1,

SUM_REF_REFERRINGPROVNPI1,
SUM_REF_PROVIDERINTERNALID1,
SUM_REF_PROVIDERPIDSL1,

SUM_REN_RENDERINGPROVNPI1,
SUM_REN_PROVIDERINTERNALID1,
SUM_REN_PROVIDERPIDSL1,

SUM_SUP_SUPERVISINGPROVNPI1,
SUM_SUP_PROVIDERINTERNALID1,
SUM_SUP_PROVIDERPIDSL1,

SUM_ORD_ORDERINGPROVID1,
SUM_ORD_PROVIDERINTERNALID1,
SUM_ORD_PROVIDERPIDSL1,

SUM_TOT_REX
FROM (
SELECT
RUN_DATE,
TRANSSETCONTROLNUM,
A.FILENAME,
RECORD_TYPE,
SUBMITTERID,
CASE WHEN A.CLAIM_TYPE = 'M' THEN PS."SubmitterLastOrgName"
     WHEN A.CLAIM_TYPE = 'D' THEN DS."SubmitterLastOrgName"
     ELSE S."SubmitterLastOrgName"
END AS SUBMITTERNAME,
CLAIM_TYPE,
SUM(CLAIMFREQUENCYCODE1) SUM_CLAIMFREQUENCYCODE1,
SUM(STATEMENTDTP1) SUM_STATEMENTDTP1,
SUM(ADMISSIONDTP1) SUM_ADMISSIONDTP1,
SUM(BILLINGPROVNPI1) SUM_BILLINGPROVNPI1,
SUM(ADMITTINGDIAGNOSISCODE1) SUM_ADMITTINGDIAGNOSISCODE1,
SUM(FACILITYTYPECODE1) SUM_FACILITYTYPECODE1,
SUM(ADMISSIONTYPECODE1) SUM_ADMISSIONTYPECODE1,
SUM(ADMISSIONSOURCECODE1) SUM_ADMISSIONSOURCECODE1,
SUM(SVCLINECHARGEAMT1) SUM_SVCLINECHARGEAMT1,
SUM(SVCLINEREVENUECODE1) SUM_SVCLINEREVENUECODE1,

SUM(OCCURRENCECODE1) SUM_OCCURRENCECODE1,
SUM(OCCURRENCESPANCODE1) SUM_OCCURRENCESPANCODE1,

SUM(VALUECODE1) SUM_VALUECODE1,
SUM(CONDITIONCODE1) SUM_CONDITIONCODE1,

SUM(PATIENTSTATUSCODE1) SUM_PATIENTSTATUSCODE1,
SUM(PRINCIPALDIAGNOSISCODE1) SUM_PRINCIPALDIAGNOSISCODE1,

SUM(ICD10DIAGNOSIS_CODE1) SUM_ICD10DIAGNOSIS_CODE1,

SUM(MULTIPLEPROCEDURECODE1) SUM_MULTIPLEPROCEDURECODE1,

SUM(CDT_CODE1) SUM_CDT_CODE1,
SUM(CPT_CODE1) SUM_CPT_CODE1,
SUM(HIPPS_CODE1) SUM_HIPPS_CODE1,

SUM(SVCLINEPROCMOD1) SUM_SVCLINEPROCMOD1,
SUM(SVCLINEADJREVENUECODE1) SUM_SVCLINEADJREVENUECODE1,
SUM(PROCEDURECODE1) SUM_PROCEDURECODE1,
SUM(SVCLINEADJUDICATIONPROCMOD1) SUM_SVCLINEADJUDICATIONPROCMOD1,


SUM(BILL_PROVIDERINTERNALID1) SUM_BILL_PROVIDERINTERNALID1,
SUM(BILL_PROVIDERPIDSL1) SUM_BILL_PROVIDERPIDSL1,

SUM(REF_REFERRINGPROVNPI1) SUM_REF_REFERRINGPROVNPI1,
SUM(REF_PROVIDERINTERNALID1) SUM_REF_PROVIDERINTERNALID1,
SUM(REF_PROVIDERPIDSL1) SUM_REF_PROVIDERPIDSL1,

SUM(REN_RENDERINGPROVNPI1) SUM_REN_RENDERINGPROVNPI1,
SUM(REN_PROVIDERINTERNALID1) SUM_REN_PROVIDERINTERNALID1,
SUM(REN_PROVIDERPIDSL1) SUM_REN_PROVIDERPIDSL1,

SUM(SUP_SUPERVISINGPROVNPI1) SUM_SUP_SUPERVISINGPROVNPI1,
SUM(SUP_PROVIDERINTERNALID1) SUM_SUP_PROVIDERINTERNALID1,
SUM(SUP_PROVIDERPIDSL1) SUM_SUP_PROVIDERPIDSL1,

SUM(ORD_ORDERINGPROVID1) SUM_ORD_ORDERINGPROVID1,
SUM(ORD_PROVIDERINTERNALID1) SUM_ORD_PROVIDERINTERNALID1,
SUM(ORD_PROVIDERPIDSL1) SUM_ORD_PROVIDERPIDSL1,

SUM(TOT_REX) SUM_TOT_REX
FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_BI_7M_QA A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837I_FILE_STATISTICS S
    ON A.FILENAME = S."FileName" AND A.CLAIM_TYPE IN ('I','L','O')
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837P_FILE_STATISTICS PS
    ON A.FILENAME = PS."FileName" AND A.CLAIM_TYPE = 'M'
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837D_FILE_STATISTICS DS
    ON A.FILENAME = DS."FileName" AND A.CLAIM_TYPE = 'D'    
GROUP BY
RUN_DATE,
TRANSSETCONTROLNUM,
A.FILENAME,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
RECORD_TYPE
)
ORDER BY
RUN_DATE,
TRANSSETCONTROLNUM,
FILENAME,
SUBMITTERID,
SUBMITTERNAME,
CLAIM_TYPE,
RECORD_TYPE
;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_7M_QA_UNPIV(
	RUN_DATE,
	FILENAME,
	CLAIM_TYPE,
	RECORD_TYPE,
	MEASURE,
	TYPE,
	REC_CNT,
	SUBMITTERNAME,
	BENCHMARK_THRESHOLD
) as

SELECT DISTINCT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, REC_CNT,
--SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, REC_CNT,
PS."SubmitterLastOrgName" AS SUBMITTERNAME,
L.BENCHMARK_THRESHOLD
FROM
(
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, COUNT(TYPE) AS REC_CNT
FROM (
SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    RECORD_TYPE,
    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	STATEMENTDTP1X AS Statement_Date,
	ADMISSIONDTP1X AS Admission_Date,
	ADMITTINGDIAGNOSISCODE1X AS Admitting_Diagnosis_Code,
	FACILITYTYPECODE1X AS Facility_Type_Code,
	ADMISSIONTYPECODE1X AS Admission_Type_Code,
	ADMISSIONSOURCECODE1X AS Admission_Source_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEREVENUECODE1X AS Service_Line_Revenue_Code,
	OCCURRENCECODE1X AS Occurence_Code,
	OCCURRENCESPANCODE1X AS Occurrence_Span_Code,
	VALUECODE1X AS Value_Code,
	CONDITIONCODE1X AS Condition_Code,
	PATIENTSTATUSCODE1X AS Patient_Status_Code,
	PRINCIPALDIAGNOSISCODE1X AS Principal_Diag_Code,
	ICD10DIAGNOSIS_CODE1X AS ICD10_Diag_Code,
	MULTIPLEPROCEDURECODE1X AS Service_Line_Proc_Code,
	CDT_CODE1X AS CDT_Code,
	CPT_CODE1X AS CPT_Code,
	HIPPS_CODE1X AS HIPPS_Code,
	SVCLINEPROCMOD1X AS Service_Line_Proc_Mod,
	SVCLINEADJREVENUECODE1X AS Service_Line_Adjust_Revenue_Code,
	PROCEDURECODE1X AS Procedure_Code,
	SVCLINEADJUDICATIONPROCMOD1X AS Service_Line_Adj_Proc_Mod,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    SUP_SUPERVISINGPROVNPI1X Supervising_Provider_NPI,
    SUP_PROVIDERINTERNALID1X Supervising_Provider_Internal_ID,
    SUP_PROVIDERPIDSL1X Supervising_Provider_PIDSL,

    ORD_ORDERINGPROVID1X Ordering_Provider_NPI,
    ORD_PROVIDERINTERNALID1X Ordering_Provider_Internal_ID,
    ORD_PROVIDERPIDSL1X Ordering_Provider_PIDSL

    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7M_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Statement_Date,
	Admission_Date,
	Admitting_Diagnosis_Code,
	Facility_Type_Code,
	Admission_Type_Code,
	Admission_Source_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
	Occurence_Code,
	Occurrence_Span_Code,
	Value_Code,
	Condition_Code,
	Patient_Status_Code,
	Principal_Diag_Code,
	ICD10_Diag_Code,
	Service_Line_Proc_Code,
	CDT_Code,
	CPT_Code,
	HIPPS_Code,
	Service_Line_Proc_Mod,
	Service_Line_Adjust_Revenue_Code,
	Procedure_Code,
	Service_Line_Adj_Proc_Mod,

    Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Supervising_Provider_NPI,
    Supervising_Provider_Internal_ID,
    Supervising_Provider_PIDSL,

    Ordering_Provider_NPI,
    Ordering_Provider_Internal_ID,
    Ordering_Provider_PIDSL
)
) AS INF_B_SENDPRO_CLAIMS_DQ_7M_UNPIV
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
)
GROUP BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE
) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837P_FILE_STATISTICS PS
    ON A.FILENAME = PS."FileName" AND A.CLAIM_TYPE = 'M'
JOIN INF_B_SENDPRO_LOOKUP L ON A.MEASURE = L.BENCHMARK
ORDER BY FILENAME, CLAIM_TYPE, MEASURE, TYPE;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_7_837M_UNPIV_DETAIL(
	RUN_DATE,
	FILENAME,
	CLAIM_TYPE,
	RECORD_TYPE,
	MEASURE,
	TYPE,
	PATIENTCONTROLNUM,
	NUMDTL,
	RNK,
	SUBMITTERNAME
) as

SELECT DISTINCT A.*,
PS."SubmitterLastOrgName" AS SUBMITTERNAME
FROM
(

-- limit rank to 10 lines
SELECT *
FROM (
-- rank
  SELECT *,
                                            RANK ()
                                            OVER (PARTITION BY RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE
                                                  ORDER BY
                                                               RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE,
                                                               TYPE,
                                                               PATIENTCONTROLNUM,
                                                               NUMDTL)    AS rnk

  FROM (

-- only first claim line

SELECT *
  FROM (

-- core unpiv

SELECT RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE, PatientControlNum, NumDtl  
FROM (
    SELECT
    RUN_DATE,
    FILENAME, 
    CLAIM_TYPE,
    RECORD_TYPE,
    CLAIMFREQUENCYCODE1X AS Claim_Frequency_Code,
	STATEMENTDTP1X AS Statement_Date,
	ADMISSIONDTP1X AS Admission_Date,
	ADMITTINGDIAGNOSISCODE1X AS Admitting_Diagnosis_Code,
	FACILITYTYPECODE1X AS Facility_Type_Code,
	ADMISSIONTYPECODE1X AS Admission_Type_Code,
	ADMISSIONSOURCECODE1X AS Admission_Source_Code,
	SVCLINECHARGEAMT1X AS Service_Line_Chrg_Amt,
	SVCLINEREVENUECODE1X AS Service_Line_Revenue_Code,
	OCCURRENCECODE1X AS Occurence_Code,
	OCCURRENCESPANCODE1X AS Occurrence_Span_Code,
	VALUECODE1X AS Value_Code,
	CONDITIONCODE1X AS Condition_Code,
	PATIENTSTATUSCODE1X AS Patient_Status_Code,
	PRINCIPALDIAGNOSISCODE1X AS Principal_Diag_Code,
	ICD10DIAGNOSIS_CODE1X AS ICD10_Diag_Code,
	MULTIPLEPROCEDURECODE1X AS Service_Line_Proc_Code,
	CDT_CODE1X AS CDT_Code,
	CPT_CODE1X AS CPT_Code,
	HIPPS_CODE1X AS HIPPS_Code,
	SVCLINEPROCMOD1X AS Service_Line_Proc_Mod,
	SVCLINEADJREVENUECODE1X AS Service_Line_Adjust_Revenue_Code,
	PROCEDURECODE1X AS Procedure_Code,
	SVCLINEADJUDICATIONPROCMOD1X AS Service_Line_Adj_Proc_Mod,

	BILLINGPROVNPI1X AS Bill_Provider_NPI,
    BILL_PROVIDERINTERNALID1X Bill_Provider_Internal_ID,
    BILL_PROVIDERPIDSL1X Bill_Provider_PIDSL,

    REF_REFERRINGPROVNPI1X Referring_Provider_NPI,
    REF_PROVIDERINTERNALID1X Referring_Provider_Internal_ID,
    REF_PROVIDERPIDSL1X Referring_Provider_PIDSL,

    REN_RENDERINGPROVNPI1X Rendering_Provider_NPI,
    REN_PROVIDERINTERNALID1X Rendering_Provider_Internal_ID,
    REN_PROVIDERPIDSL1X Rendering_Provider_PIDSL,

    SUP_SUPERVISINGPROVNPI1X Supervising_Provider_NPI,
    SUP_PROVIDERINTERNALID1X Supervising_Provider_Internal_ID,
    SUP_PROVIDERPIDSL1X Supervising_Provider_PIDSL,

    ORD_ORDERINGPROVID1X Ordering_Provider_NPI,
    ORD_PROVIDERINTERNALID1X Ordering_Provider_Internal_ID,
    ORD_PROVIDERPIDSL1X Ordering_Provider_PIDSL,
    
    PatientControlNum, 
    NumDtl
    FROM MHTEAM.DWDQ.INF_SENDPRO_CLAIMS_DQ_QA_7M_QA
)
UNPIVOT (
TYPE
FOR MEASURE IN (
	Claim_Frequency_Code,
	Statement_Date,
	Admission_Date,
	Admitting_Diagnosis_Code,
	Facility_Type_Code,
	Admission_Type_Code,
	Admission_Source_Code,
	Service_Line_Chrg_Amt,
	Service_Line_Revenue_Code,
	Occurence_Code,
	Occurrence_Span_Code,
	Value_Code,
	Condition_Code,
	Patient_Status_Code,
	Principal_Diag_Code,
	ICD10_Diag_Code,
	Service_Line_Proc_Code,
	CDT_Code,
	CPT_Code,
	HIPPS_Code,
	Service_Line_Proc_Mod,
	Service_Line_Adjust_Revenue_Code,
	Procedure_Code,
	Service_Line_Adj_Proc_Mod,

    Bill_Provider_NPI,
    Bill_Provider_Internal_ID,
    Bill_Provider_PIDSL,

    Referring_Provider_NPI,
    Referring_Provider_Internal_ID,
    Referring_Provider_PIDSL,

    Rendering_Provider_NPI,
    Rendering_Provider_Internal_ID,
    Rendering_Provider_PIDSL,

    Supervising_Provider_NPI,
    Supervising_Provider_Internal_ID,
    Supervising_Provider_PIDSL,

    Ordering_Provider_NPI,
    Ordering_Provider_Internal_ID,
    Ordering_Provider_PIDSL

)
) AS UNPIV7M
ORDER BY RUN_DATE, FILENAME, CLAIM_TYPE, RECORD_TYPE, MEASURE, TYPE

)
-- only first claim line
    WHERE NUMDTL = 1
    )
-- add rank
)
-- limit rank to 10 line
WHERE rnk <= 10

) A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_837P_FILE_STATISTICS PS
    ON A.FILENAME = PS."FileName" AND A.CLAIM_TYPE = 'M'
ORDER BY 
                                                               RUN_DATE,
                                                               FILENAME,
                                                               CLAIM_TYPE,
                                                               RECORD_TYPE,
                                                               MEASURE,
                                                               TYPE,
                                                               PATIENTCONTROLNUM,
                                                               RNK
;

--------------  NCPDP

create or replace view MHTEAM.DWDQ.INF_SENDPRO_NCPDP_DQ_QA_7_QA(
	RUN_DATE,
	CLAIM_TYPE,
	FILENAME,
	PAHDRSENDINGENTITYID,
	SUBSCRIBERMEMBERID,
	NUMDTL,
	DOS,
	NDCSERV,
	SERVPROVNPI,
	SERVPROVSECID,
	PRESCRIBERNPI,
	PRESCRIBERSECID,
	SUBSCRIBERMEMBERID1X,
	NDCSERV1X,
	COMPNDPRODCODE1X,
	ADJUDICATIONDATE1X,
	SERVPROVNPI1X,
	SERVPROVSECID1X,
	PRESCRIBERNPI1X,
	PRESCRIBERSECID1X
) as
SELECT
RUN_DATE,
claim_type,
Filename,
PAHdrSendingEntityID,
SubscriberMemberID,
Numdtl,
DOS,
NDCServ,
ServProvNPI,
ServProvSecID,
PrescriberNPI,
PrescriberSecID,
	SUBSCRIBERMEMBERID1X,
	NDCSERV1X,
	COMPNDPRODCODE1X,
	ADJUDICATIONDATE1X,
	SERVPROVNPI1X,
	SERVPROVSECID1X,
    PRESCRIBERNPI1X,
    PRESCRIBERSECID1X
FROM MHTEAM.DWDQ.INF_B_SENDPRO_NCPDP_DQ_7_QA;

create or replace view MHTEAM.DWDQ.INF_SENDPRO_NCPDP_DQ_BI_STATS_7_QA(
	RUN_DATE,
	CLAIM_TYPE,
	FILENAME,
	PAHDRSENDINGENTITYID,
	PCT_SUBSCRIBERMEMBERID1,
	PCT_NDCSERV1,
	PCT_COMPNDPRODCODE1,
	PCT_ADJUDICATIONDATE1,
	PCT_SERVPROVNPI1,
	PCT_SERVPROVSECID1,
	PCT_PRESCRIBERNPI1,
	PCT_PRESCRIBERSECID1,
	SUM_SUBSCRIBERMEMBERID1,
	SUM_NDCSERV1,
	SUM_COMPNDPRODCODE1,
	SUM_ADJUDICATIONDATE1,
	SUM_SERVPROVNPI1,
	SUM_SERVPROVSECID1,
	SUM_PRESCRIBERNPI1,
	SUM_PRESCRIBERSECID1,
	SUM_TOT_REX
) as
SELECT DISTINCT
RUN_DATE,
claim_type,
Filename,
PAHdrSendingEntityID,

SUM_SUBSCRIBERMEMBERID1/SUM_TOT_REX PCT_SUBSCRIBERMEMBERID1,
SUM_NDCSERV1/SUM_TOT_REX PCT_NDCSERV1,
SUM_COMPNDPRODCODE1/SUM_TOT_REX PCT_COMPNDPRODCODE1,
SUM_ADJUDICATIONDATE1/SUM_TOT_REX PCT_ADJUDICATIONDATE1,
SUM_SERVPROVNPI1/SUM_TOT_REX PCT_SERVPROVNPI1,
SUM_SERVPROVSECID1/SUM_TOT_REX PCT_SERVPROVSECID1,
SUM_PRESCRIBERNPI1/SUM_TOT_REX PCT_PRESCRIBERNPI1,
SUM_PRESCRIBERSECID1/SUM_TOT_REX PCT_PRESCRIBERSECID1,

SUM_SUBSCRIBERMEMBERID1,
SUM_NDCSERV1,
SUM_COMPNDPRODCODE1,
SUM_ADJUDICATIONDATE1,
SUM_SERVPROVNPI1,
SUM_SERVPROVSECID1,
SUM_PRESCRIBERNPI1,
SUM_PRESCRIBERSECID1,

SUM_TOT_REX
FROM (
SELECT
RUN_DATE,
claim_type,
Filename,
PAHdrSendingEntityID,
SUM(SUBSCRIBERMEMBERID1) SUM_SUBSCRIBERMEMBERID1,
SUM(NDCSERV1) SUM_NDCSERV1,
SUM(COMPNDPRODCODE1) SUM_COMPNDPRODCODE1,
SUM(ADJUDICATIONDATE1) SUM_ADJUDICATIONDATE1,
SUM(SERVPROVNPI1) SUM_SERVPROVNPI1,
SUM(SERVPROVSECID1) SUM_SERVPROVSECID1,
SUM(PRESCRIBERNPI1) SUM_PRESCRIBERNPI1,
SUM(PRESCRIBERSECID1) SUM_PRESCRIBERSECID1,
SUM(TOT_REX) SUM_TOT_REX
FROM MHTEAM.DWDQ.INF_SENDPRO_NCPDP_DQ_BI_7_QA A
LEFT JOIN MHDWQA.SENDPRO.RAW_SPRO_NCPDP_STATISTICS S
--ON  A.SendProTransId       = S."SendProTransId"
--AND A.PAHdrSendingEntityID = S."PAHdrSendingEntityID"
--AND A.PAHdrBatchNum        = S."PAHdrBatchNum"
ON A.Filename             = S."FileName"

GROUP BY
RUN_DATE,
claim_type,
Filename,
PAHdrSendingEntityID
)
ORDER BY
RUN_DATE,
claim_type,
Filename
;




